import {test,expect,type Page} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const state=(p:Page)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
const mouse=async(p:Page,button:'left'|'right'='left')=>{await p.mouse.down({button});await p.mouse.up({button});};
async function aim(p:Page,which:'tables'|'chests'){await p.evaluate(which=>{const g=(window as any).__LAST_NIGHT__,s=g.state(),t=s.crafting[which][0];g.setLook(Math.atan2(t.x-s.player.x,t.z-s.player.z),Math.atan2(t.y+(which==='tables'?1:.5)-s.player.eyeY,Math.hypot(t.x-s.player.x,t.z-s.player.z)));},which);}
test('craft and place chest, open with E, split stacks, drag, transfer weapons, close and reopen',async({page:p})=>{
 const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewportSize({width:1600,height:900});await p.addInitScript(()=>{localStorage.setItem('last-night-settings',JSON.stringify({quality:'medium',master:0}));window.addEventListener('mousemove',e=>{if(document.pointerLockElement)e.stopImmediatePropagation();},true);});await p.goto('/?test');await expect(p.locator('#start')).toBeEnabled({timeout:90000});await p.locator('#start').click();await expect(p.locator('#loading-screen')).toBeHidden({timeout:90000});
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(1,12);g.setLook(0,0);g.setInventory({wood:14,scrap:5});});await p.keyboard.press('Tab');await p.locator('#craft-tab').click();await p.locator('[data-craft="bench"]').click();await p.locator('#place-bench').click();await mouse(p);await expect.poll(async()=>(await state(p)).crafting.tables.length).toBe(1);await aim(p,'tables');await p.keyboard.press('KeyE');await expect(p.locator('#workbench-screen')).toBeVisible();await p.locator('[data-recipe="chest"]').click();await p.locator('[data-craft="chest"]').click();await expect.poll(async()=>(await state(p)).inventory.chest).toBe(1);await p.keyboard.press('Escape');
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setLook(Math.PI/2,0);});await p.keyboard.press('Tab');await p.locator('#supplies-tab').click();await p.locator('#place-chest').click();await mouse(p);await expect.poll(async()=>(await state(p)).crafting.chests.length).toBe(1);await aim(p,'chests');await p.keyboard.press('KeyE');await expect(p.locator('#chest-screen')).toBeVisible();await expect(p.locator('[data-chest-slot]')).toHaveCount(27);
 await p.locator('[data-bag-item="ammo"]').click({modifiers:['Shift']});await expect.poll(async()=>(await state(p)).crafting.chests[0].slots[0]?.amount).toBe(60);await p.locator('[data-chest-slot="0"]').click({button:'right'});await p.locator('[data-chest-slot="1"]').click();await expect.poll(async()=>(await state(p)).crafting.chests[0].slots[1]?.amount).toBe(30);
 await p.locator('[data-chest-slot="1"]').dragTo(p.locator('[data-chest-slot="2"]'));await expect.poll(async()=>(await state(p)).crafting.chests[0].slots[2]?.amount).toBe(30);await p.locator('[data-bag-weapon="1"]').click({modifiers:['Shift']});await expect.poll(async()=>(await state(p)).activeSlot).toBe(3);await expect(p.locator('#chest-reclaim')).toBeDisabled();
 await mkdir('docs/chests',{recursive:true});await p.screenshot({path:'docs/chests/chest-inventory.png'});await p.keyboard.press('Escape');await expect(p.locator('#chest-screen')).toBeHidden();await expect(async()=>{if(!(await state(p)).camera.pointerLocked)await p.locator('#capture-mouse').press('Enter');expect((await state(p)).camera.pointerLocked).toBe(true);}).toPass({intervals:[300,1000],timeout:5000});await p.keyboard.press('KeyE');await expect(p.locator('#chest-screen')).toBeVisible();await p.locator('[data-chest-slot="1"]').click({modifiers:['Shift']});await expect.poll(async()=>(await state(p)).activeSlot).toBe(1);await p.locator('[data-chest-slot="0"]').click({modifiers:['Shift']});await p.locator('[data-chest-slot="2"]').click({modifiers:['Shift']});await expect.poll(async()=>(await state(p)).inventory.ammo).toBe(60);
 for(const size of [{width:1366,height:768},{width:1920,height:1080}]){await p.setViewportSize(size);expect(await p.locator('.chest-window').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await expect(p.locator('[data-chest-slot="26"]')).toBeInViewport();}
 await p.locator('#chest-reclaim').click();await expect.poll(async()=>(await state(p)).crafting.chests.length).toBe(0);await expect.poll(async()=>(await state(p)).inventory.chest).toBe(1);expect(errors).toEqual([]);
});
test('two Photon clients share placed chest inventory and retain it through host migration',async({browser})=>{
 const contexts=await Promise.all([browser.newContext({viewport:{width:1366,height:768}}),browser.newContext({viewport:{width:1366,height:768}})]),pages=await Promise.all(contexts.map(c=>c.newPage()));const errors:string[]=[];
 try{
 for(const [i,p] of pages.entries()){p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(i=>{localStorage.setItem('last-night-settings',JSON.stringify({quality:'medium',master:0}));localStorage.setItem('last-night-player-name',`Chest ${i+1}`);window.addEventListener('mousemove',e=>{if(document.pointerLockElement)e.stopImmediatePropagation();},true);},i);await p.goto('/?test');await expect(p.locator('#coop-online')).toBeEnabled({timeout:90000});await p.locator('#coop-online').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});}
 const [a,b]=pages;await a.locator('#coop-create').click();await expect(a.locator('#coop-lobby')).toBeVisible();await b.locator('#coop-code-input').fill(await a.locator('#coop-room-code').innerText());await b.locator('#coop-join').click();await expect(b.locator('#coop-lobby')).toBeVisible();await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await a.locator('#coop-start').click();for(const p of pages)await expect.poll(async()=>(await state(p)).network.state,{timeout:90000}).toBe('playing');
 await a.evaluate(async()=>{const g=(window as any).__LAST_NIGHT__,w=g.coopFixture();const {CITY_SITES}=await import('/src/game/city.ts');w.sim.zombies=[];w.sim.activatedSites=new Set(CITY_SITES.map(s=>s.id));for(const a of w.actors.values()){a.sim.inventory.items.chest=1;a.sim.inventory.items.wood=8;}});
 async function capture(p:Page){await p.bringToFront();if((await state(p)).paused)await p.locator('#resume').press('Enter');else if(!(await state(p)).camera.pointerLocked)await p.locator('#capture-mouse').press('Enter');await expect.poll(async()=>(await state(p)).camera.pointerLocked).toBe(true);}
 await capture(a);await a.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(1,12);g.setLook(0,0);});await expect.poll(async()=>(await state(a)).inventory.chest).toBe(1);await a.keyboard.press('Tab');await a.locator('#place-chest').click();await mouse(a);for(const p of pages)await expect.poll(async()=>(await state(p)).crafting.chests.length).toBe(1);
 await aim(a,'chests');await a.keyboard.press('KeyE');await expect(a.locator('#chest-screen')).toBeVisible();await a.locator('[data-bag-item="wood"]').click({modifiers:['Shift']});for(const p of pages)await expect.poll(async()=>(await state(p)).crafting.chests[0].slots[0]?.amount).toBe(8);
 await capture(b);await b.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(2,12);});await aim(b,'chests');await b.keyboard.press('KeyE');await expect(b.locator('#chest-screen')).toBeVisible();await b.locator('[data-chest-slot="0"]').click({button:'right'});await b.locator('#chest-bag [data-bag-empty]').first().click();for(const p of pages)await expect.poll(async()=>(await state(p)).crafting.chests[0].slots[0]?.amount).toBe(4);await expect.poll(async()=>(await state(b)).inventory.wood).toBe(12);
 await b.screenshot({path:'docs/chests/coop-chest.png'});await a.bringToFront();await a.locator('#chest-close').click();await capture(a);await a.keyboard.press('Escape');await a.locator('#pause-menu').click();await expect.poll(async()=>(await state(b)).coop.migrations).toBe(1);await expect.poll(async()=>(await state(b)).crafting.chests[0].slots[0]?.amount).toBe(4);await b.bringToFront();await b.locator('[data-chest-slot="0"]').click({modifiers:['Shift']});await expect.poll(async()=>(await state(b)).inventory.wood).toBe(16);await expect.poll(async()=>(await state(b)).crafting.chests[0].slots[0]).toBe(null);expect(errors).toEqual([]);
 }finally{for(const context of contexts)await context.close();}
});
