import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const state=(p:any)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
async function start(page:any){await mkdir('docs/city',{recursive:true});await page.goto('/?test');await page.locator('#start').click();await page.addStyleTag({content:'#debug-stats{display:none}'});await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPhase('dusk');});}
async function settle(page:any,x:number,z:number){await page.evaluate(([x,z]:number[])=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(x,z);g.setPhase('dusk');g.setHealth(100);g.clearWalkers();},[x,z]);await page.waitForFunction(()=>{const g=(window as any).__LAST_NIGHT__,s=g.state(),p=g.project(s.player.x,s.player.z);return Math.abs(p.x-innerWidth/2)<70&&Math.abs(p.y-innerHeight/2)<70;},null,{timeout:30000});}
async function walk(page:any,x:number,z:number){await page.evaluate(([x,z]:number[])=>{const g=(window as any).__LAST_NIGHT__;const path=g.pathTo(x,z);const r={done:false,failed:!path.length,keys:[]as string[],path};(window as any).__cityWalk=r;const keys=(next:string[])=>{for(const code of r.keys)if(!next.includes(code))window.dispatchEvent(new KeyboardEvent('keyup',{code}));for(const code of next)if(!r.keys.includes(code))window.dispatchEvent(new KeyboardEvent('keydown',{code}));r.keys=next;};const tick=()=>{const s=g.state();if(s.gameOver||r.failed){keys([]);r.failed=true;r.done=true;return;}while(r.path.length&&Math.hypot(r.path[0].x-s.player.x,r.path[0].z-s.player.z)<.5)r.path.shift();if(!r.path.length){keys([]);r.done=true;return;}const p=r.path[0],dx=p.x-s.player.x,dz=p.z-s.player.z,n=Math.hypot(dx,dz),h=(dx-dz)/n,v=(dx+dz)/n;keys([...(h>.35?['KeyD']:h<-.35?['KeyA']:[]),...(v>.35?['KeyS']:v<-.35?['KeyW']:[])]);requestAnimationFrame(tick);};requestAnimationFrame(tick);},[x,z]);await page.waitForFunction(()=>(window as any).__cityWalk.done,null,{timeout:60000});expect(await page.evaluate(()=>(window as any).__cityWalk.failed)).toBe(false);}

test('city regions, hospital routes, industry, quarantine and map have bounded rendering',async({page})=>{
 test.setTimeout(300000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);const metrics:any[]=[];
 for(const [id,x,z]of [['residential',-113,-57],['hospital',112,-94],['industry',113,94],['quarantine',114,146],['school',-112,-96],['market',-113,82],['cemetery',-56,137]]as const){await settle(page,x,z);await walk(page,x+3,z);await page.evaluate(()=>(window as any).__LAST_NIGHT__.clearWalkers());await page.waitForTimeout(1200);const s=await state(page);expect(s.render.activeChunks).toBeLessThan(18);expect(s.render.geometryMB).toBeLessThan(25);expect(s.calls).toBeLessThan(600);metrics.push({id,player:s.player,calls:s.calls,triangles:s.triangles,active:s.zombies.length,dormant:s.dormant,fps:s.fps,...s.render,audio:s.audio});await page.screenshot({path:`docs/city/${id}.png`});}
 await page.locator('#map-toggle').click();await expect(page.locator('#map-screen')).toBeVisible();await page.screenshot({path:'docs/city/map.png'});await writeFile('docs/city/performance.json',JSON.stringify({renderer:'Chromium / SwiftShader software',viewport:'1440×900',metrics},null,2));expect(errors).toEqual([]);
});
test('hospital entry, furnished interior, side escape, boarding and stash work through controls',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);await settle(page,112,-97.5);await expect(page.locator('#interaction')).toContainText('PORTA');await page.keyboard.press('e');await expect.poll(async()=>(await state(page)).portals.find((p:any)=>p.id==='hospital-main-front').state,{timeout:15000}).toBe('open');await walk(page,112,-105);await page.evaluate(()=>(window as any).__LAST_NIGHT__.clearWalkers());await page.screenshot({path:'docs/city/hospital-interior.png'});
 await walk(page,110,-105.5);await page.keyboard.press('e');await expect.poll(async()=>(await state(page)).loot.find((p:any)=>p.id==='hospital-main-entry').searched,{timeout:15000}).toBe(true);
 await walk(page,125.5,-112);await page.keyboard.press('e');await expect.poll(async()=>(await state(page)).portals.find((p:any)=>p.id==='hospital-main-side').state,{timeout:15000}).toBe('open');await walk(page,129,-112);await page.keyboard.press('x');await expect.poll(async()=>(await state(page)).portals.find((p:any)=>p.id==='hospital-main-side').state,{timeout:15000}).toBe('barred');await page.screenshot({path:'docs/city/window-barricade.png'});
 await settle(page,1,7);await page.evaluate(()=>(window as any).__LAST_NIGHT__.dropWeapon('rifle',1,8,'rare'));await page.keyboard.press('e');await expect.poll(async()=>(await state(page)).weapon.type).toBe('rifle');await page.keyboard.press('Tab');await page.locator('#equipment-tab').click();await page.locator('[data-store="0"]').click();await expect.poll(async()=>(await state(page)).weaponStorage.length).toBe(1);await page.screenshot({path:'docs/city/weapon-stash.png'});await page.locator('[data-retrieve]').click();await expect.poll(async()=>(await state(page)).weaponStorage.length).toBe(0);expect((await state(page)).weapon.rarity).toBe('rare');expect(errors).toEqual([]);
});
test('Screamer windup completes, attracts existing zombies, then a real shot interrupts another cry',async({page})=>{
 test.setTimeout(90000);await start(page);await settle(page,1,7);await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.spawn(1,14,'screamer');g.spawn(36,15);});await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().zombies.some((z:any)=>z.screamTimer>0));await page.screenshot({path:'docs/city/screamer-telegraph.png'});await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().zombies.some((z:any)=>z.screamCooldown>10));expect((await state(page)).zombies.find((z:any)=>z.kind==='walker').hearing).toBeGreaterThan(0);await page.screenshot({path:'docs/city/screamer-call.png'});
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.spawn(1,14,'screamer');});await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().zombies.some((z:any)=>z.screamTimer>0));const p=await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__,z=g.state().zombies.find((z:any)=>z.kind==='screamer');return g.project(z.x,z.z,1.3);});await page.mouse.click(p.x,p.y);await page.waitForFunction(()=>{const z=(window as any).__LAST_NIGHT__.state().zombies.find((z:any)=>z.kind==='screamer');return !z||z.hp<65&&!z.screamTimer;});await page.screenshot({path:'docs/city/screamer-interrupted.png'});
});
test('roaming walkers cross the street; night outside persists and advanced siege retains its budget',async({page})=>{
 test.setTimeout(180000);await start(page);await settle(page,88,-30);const count=await page.evaluate(()=>(window as any).__LAST_NIGHT__.spawnRoaming());expect(count).toBe(10);await page.screenshot({path:'docs/city/roaming-route.png'});await page.evaluate(()=>(window as any).__LAST_NIGHT__.setPhase('preparation',29));await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().phase==='night');const before=await state(page);await page.waitForFunction(t=>(window as any).__LAST_NIGHT__.state().stats.seconds>t+8,before.stats.seconds,{timeout:30000});const after=await state(page);expect(after.gameOver).toBe(false);expect(after.player.hp).toBeGreaterThan(0);await page.screenshot({path:'docs/city/outside-night.png'});
 // Controlled return fixture: traversal itself is covered separately by the keyboard expedition.
 await settle(page,1,12);await page.evaluate(()=>(window as any).__LAST_NIGHT__.setPhase('night'));await walk(page,1,7);expect((await state(page)).horde.budget).toBe(22);
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setDay(5);g.setPhase('night');g.setSpeed(6);});await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().horde.spawned>=12,null,{timeout:30000});const advanced=await state(page);expect(advanced.horde.budget).toBe(58);expect(advanced.zombies.length).toBeLessThanOrEqual(40);await page.evaluate(()=>(window as any).__LAST_NIGHT__.setSpeed(1));await page.screenshot({path:'docs/city/night-five.png'});await writeFile('docs/city/night-scenarios.json',JSON.stringify({before,after,advanced},null,2));
});
