import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const state=(p:Page)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
async function capture(p:Page){await p.bringToFront();if((await state(p)).paused)await p.locator('#resume').press('Enter');else if(!(await state(p)).camera.pointerLocked)await p.locator('#capture-mouse').press('Enter');await expect.poll(async()=>(await state(p)).camera.pointerLocked).toBe(true);}
async function placePlayer(p:Page,x:number,z:number,yaw=0,pitch=0){await p.evaluate(({x,z,yaw,pitch})=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(x,z);g.setLook(yaw,pitch);},{x,z,yaw,pitch});await expect.poll(async()=>{const s=await state(p),actor=s.coop?.players?.find((a:any)=>a.actor===s.coop.actor);return actor?Math.hypot(actor.player.x-x,actor.player.z-z):Infinity;}).toBeLessThan(.2);}
async function aim(p:Page,x:number,z:number,y:number){await p.evaluate(({x,z,y})=>{const g=(window as any).__LAST_NIGHT__,s=g.state();g.setLook(Math.atan2(x-s.player.x,z-s.player.z),Math.atan2(y-s.player.eyeY,Math.hypot(x-s.player.x,z-s.player.z)));},{x,z,y});await p.waitForTimeout(100);}
async function both(pages:Page[],predicate:(s:any)=>unknown,expected:unknown){for(const p of pages)await expect.poll(async()=>predicate(await state(p))).toEqual(expected);}

for(const mode of ['photon','lan'] as const)test(`${mode}: hammer building, fortification and a full chest survive host migration`,async({browser})=>{
 const startedAt=Date.now(),contexts=await Promise.all([browser.newContext(),browser.newContext()]),pages=await Promise.all(contexts.map(c=>c.newPage())),errors:string[]=[],sockets:string[]=[];
 const [a,b]=pages;
 try{
  for(const [i,p] of pages.entries()){
   p.on('pageerror',e=>errors.push(e.message));p.on('websocket',s=>sockets.push(s.url()));
   await p.addInitScript(i=>{localStorage.setItem('last-night-settings',JSON.stringify({quality:'low',master:0}));localStorage.setItem('last-night-player-name',`Build ${i+1}`);window.addEventListener('mousemove',e=>{if(document.pointerLockElement)e.stopImmediatePropagation();},true);},i);
   await p.goto(`/?test&coop=${mode}`);await expect(p.locator('#coop-online')).toBeEnabled({timeout:90000});await p.locator('#coop-online').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});
  }
  await a.locator('#coop-create').click();
  if(mode==='photon'){
   await expect(a.locator('#coop-lobby')).toBeVisible();await b.locator('#coop-code-input').fill(await a.locator('#coop-room-code').innerText());await b.locator('#coop-join').click();await expect(b.locator('#coop-lobby')).toBeVisible();await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await a.locator('#coop-start').click();
  }else{
   await expect(a.locator('#loading-screen')).toBeHidden({timeout:90000});await capture(a);await a.keyboard.press('Escape');await a.locator('#pause-lan').click();await expect(a.locator('#pause-lan-code')).toBeVisible({timeout:45000});await b.locator('#coop-code-input').fill(await a.locator('#pause-lan-code').inputValue());await b.locator('#coop-join').click();
  }
  for(const p of pages)await expect.poll(async()=>(await state(p)).network.state,{timeout:90000}).toBe('playing');
  await a.evaluate(async()=>{const g=(window as any).__LAST_NIGHT__,w=g.coopFixture(),{CITY_SITES}=await import('/src/game/city.ts');w.sim.zombies=[];w.sim.spawnTimer=10000;w.sim.activatedSites=new Set(CITY_SITES.map(s=>s.id));w.sim.crafting.tables.push({id:w.sim.crafting.next++,x:3.5,z:4,y:.22,angle:0,hp:200});w.sim.crafting.revision++;for(const a of w.actors.values()){a.sim.inventory.items.chest=1;Object.assign(a.sim.inventory.items,{wood:8,scrap:6,cloth:4,cord:1});a.sim.player.invulnerable=99;if(a.actor===g.state().coop.actor){a.sim.inventory.items.wood+=3;a.sim.inventory.items.scrap+=5;a.sim.inventory.items.cloth++;}else a.sim.gear.owned.push('hammer');}});
  await both(pages,s=>s.crafting.tables.length,1);
  await capture(a);await placePlayer(a,3.5,6.5,Math.PI,0);await aim(a,3.5,4,1.32);await a.keyboard.press('KeyE');await expect(a.locator('#workbench-screen')).toBeVisible();await a.locator('#recipe-category').selectOption('Construção');
  await expect(a.locator('[data-recipe="build-wall"]')).toHaveCount(0);await a.locator('[data-recipe="hammer"]').click();await expect(a.locator('#bench-craft')).toBeEnabled();await a.locator('#bench-craft').click();await expect(a.locator('#workbench-screen')).toBeHidden();
  await expect.poll(async()=>{const s=await state(a);return s.activeSlot===2&&s.gear.melee==='hammer';}).toBe(true);await capture(a);await expect(a.locator('#build-hotbar')).toBeVisible();await expect(a.locator('[data-build-kind]')).toHaveCount(9);
  await expect.poll(async()=>{const s=await state(b);return s.coop.players.some((r:any)=>r.actor!==s.coop.actor&&r.activeSlot===2&&r.gear.melee==='hammer');}).toBe(true);
  await a.keyboard.press('Digit2');await expect(a.locator('[data-build-kind="window"]')).toHaveAttribute('aria-pressed','true');await a.keyboard.press('Digit1');await expect(a.locator('[data-build-kind="wall"]')).toHaveAttribute('aria-pressed','true');
  await placePlayer(a,-3.5,7,Math.PI,-.55);await expect(a.locator('#build-status')).toHaveText(/Encaixe livre/);await a.mouse.click(450,350);await both(pages,s=>s.crafting.structures.length,1);await a.keyboard.press('KeyB');await expect(a.locator('#build-hotbar')).toBeHidden();await expect.poll(async()=>(await state(a)).activeSlot).toBe(1);
  const built=(await state(a)).crafting.structures[0];expect(built.kind).toBe('wall');expect(built.hp).toBe(300);
  await capture(b);await b.keyboard.press('KeyB');await expect(b.locator('#build-hotbar')).toBeVisible();await placePlayer(b,-3.5,6.4,Math.PI,0);await aim(b,built.x,built.z,1.7);await b.keyboard.press('KeyG');await expect(b.locator('#construction-screen')).toBeVisible();await b.locator('#construction-fortify').click();await both(pages,s=>s.crafting.structures[0].tier,1);await both(pages,s=>s.crafting.structures[0].hp,540);await b.keyboard.press('Escape');await capture(b);await b.keyboard.press('KeyB');await expect(b.locator('#build-hotbar')).toBeHidden();
  await capture(a);await placePlayer(a,1,12);await a.keyboard.press('Tab');await a.locator('#place-chest').click();await capture(a);await a.mouse.click(450,350);await both(pages,s=>s.crafting.chests.length,1);
  const chest=(await state(a)).crafting.chests[0];await capture(b);await placePlayer(b,2,12);await aim(b,chest.x,chest.z,chest.y+.6);await b.keyboard.press('KeyE');await expect(b.locator('#chest-screen')).toBeVisible();await b.locator('[data-bag-item="ammo"]').click({modifiers:['Shift']});await both(pages,s=>s.crafting.chests[0].slots[0]?.amount,60);await b.keyboard.press('Escape');
  await capture(a);await aim(a,chest.x,chest.z,chest.y+.6);await a.keyboard.press('KeyE');await expect(a.locator('#chest-screen')).toBeVisible();const loaded=(await state(a)).crafting.chests[0];await a.locator('#chest-relocate').click();await capture(a);await aim(a,2,14.75,.22);await a.keyboard.press('KeyR');await a.mouse.click(450,350);await both(pages,s=>s.crafting.chests[0].revision,loaded.revision+1);
  const moved=(await state(a)).crafting.chests[0];expect(moved.id).toBe(loaded.id);expect(moved.x).not.toBe(loaded.x);expect(moved.slots).toEqual(loaded.slots);await both(pages,s=>s.crafting.chests[0],moved);
  await capture(b);await placePlayer(b,moved.x,moved.z-2);await aim(b,moved.x,moved.z,moved.y+.6);await b.keyboard.press('KeyE');await expect(b.locator('#chest-screen')).toBeVisible();await expect(b.locator('[data-chest-slot="0"] strong')).toHaveText('60');
  await mkdir('docs/construction',{recursive:true});await b.screenshot({path:`docs/construction/${mode}-shared-chest.png`});
  await capture(a);await a.keyboard.press('Escape');await a.locator('#pause-menu').click();await expect.poll(async()=>(await state(b)).coop.migrations,{timeout:30000}).toBe(1);await expect.poll(async()=>(await state(b)).network.players.length).toBe(1);expect((await state(b)).crafting.chests[0]).toEqual(moved);expect((await state(b)).crafting.structures[0].tier).toBe(1);
  await b.bringToFront();await b.locator('[data-chest-slot="0"]').click({modifiers:['Shift']});await expect.poll(async()=>(await state(b)).inventory.ammo).toBe(60);await expect.poll(async()=>(await state(b)).crafting.chests[0].slots[0]).toBe(null);expect((await state(b)).gear.owned).toContain('hammer');await b.keyboard.press('Escape');await capture(b);await b.keyboard.press('KeyB');await expect(b.locator('#build-hotbar')).toBeVisible();await expect(b.locator('[data-build-kind="wall"]')).toHaveAttribute('aria-pressed','true');await expect.poll(async()=>(await state(b)).switchTimer).toBe(0);await b.keyboard.press('Digit0');await expect(b.locator('#build-hotbar')).toBeHidden();expect(errors).toEqual([]);
  if(mode==='lan')expect(sockets.every(s=>!s.includes('photon'))).toBe(true);
  await writeFile(`docs/construction/${mode}-network-validation.json`,JSON.stringify({mode,players:2,elapsedSeconds:(Date.now()-startedAt)/1000,errors,hammerCraftedAtWorkbench:true,hammerHotbar:true,remoteHammerEquipped:true,hammerSurvivesMigration:true,building:true,remoteFortification:true,openWithE:true,relocateFullChest:true,hostMigration:true,websocketHosts:[...new Set(sockets.map(s=>new URL(s).host))]},null,2));
 }finally{for(const c of contexts)await c.close();}
});
