import {test,expect,type Browser,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const evidenceDir=process.env.COOP_EVIDENCE_DIR??'docs/phase10b';
const wire=new WeakMap<Page,{tx:number;rx:number;start:number;receivedAt:number[]}>();
async function renderer(p:Page){return p.evaluate(()=>{const gl=document.querySelector('canvas')!.getContext('webgl2')!;const info=gl.getExtension('WEBGL_debug_renderer_info');return info?gl.getParameter(info.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);});}
function jitter(times:number[],since:number){const t=times.filter(v=>v>=since),gaps=t.slice(1).map((v,i)=>v-t[i]);const mean=gaps.reduce((a,b)=>a+b,0)/Math.max(1,gaps.length);return {samples:gaps.length,meanMs:mean,standardDeviationMs:Math.sqrt(gaps.reduce((a,b)=>a+(b-mean)**2,0)/Math.max(1,gaps.length)),maxMs:Math.max(0,...gaps)};}
const read=(p:Page)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
async function client(browser:Browser,name:string){
 const context=await browser.newContext({viewport:{width:960,height:640},deviceScaleFactor:process.env.LAST_NIGHT_GPU==='1'?1:.5});const p=await context.newPage();p.setDefaultTimeout(45000);const traffic={tx:0,rx:0,start:Date.now(),receivedAt:[] as number[]};wire.set(p,traffic);p.on('websocket',socket=>{if(!/photonengine|exitgames/.test(socket.url()))return;socket.on('framesent',f=>traffic.tx+=Buffer.byteLength(f.payload));socket.on('framereceived',f=>{traffic.rx+=Buffer.byteLength(f.payload);traffic.receivedAt.push(Date.now());if(traffic.receivedAt.length>5000)traffic.receivedAt.shift();});});
 await p.addInitScript(name=>{localStorage.setItem('last-night-settings',JSON.stringify({quality:'low',shadows:false,master:.1}));localStorage.setItem('last-night-player-name',name);},name);
 await p.goto('/?test',{waitUntil:'domcontentloaded',timeout:90000});await p.locator('#coop-online').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});return p;
}
async function room(browser:Browser,count:number){
 const pages:Page[]=[];const errors:string[]=[];for(let i=0;i<count;i++){const p=await client(browser,`Sobrevivente ${i+1}`);console.log('Connected client',i+1);p.on('pageerror',e=>errors.push(e.message));pages.push(p);}
 const [a]=pages;await a.locator('#coop-create').click();await expect(a.locator('#coop-lobby')).toBeVisible();const code=await a.locator('#coop-room-code').innerText();
 for(const p of pages.slice(1)){await p.locator('#coop-code-input').fill(code);await p.locator('#coop-join').click();await expect(p.locator('#coop-lobby')).toBeVisible();await p.locator('#coop-ready').click();}
 await expect(a.locator('#coop-start')).toBeEnabled();await a.locator('#coop-start').click();for(const p of pages){await expect.poll(async()=>(await read(p)).network.state,{timeout:60000}).toBe('playing');await expect.poll(async()=>(await read(p)).coop?.revision??0).toBeGreaterThan(0);}
 console.log(`${count} genuine Photon clients playing`);
 // Fixture only arranges a reproducible encounter on the actual coordinator. All replication uses Photon.
 await a.evaluate(async()=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const {CITY_SITES}=await import('/src/game/city.ts');w.sim.zombies=[];w.sim.activatedSites=new Set(CITY_SITES.map(s=>s.id));});
 await mkdir(evidenceDir,{recursive:true});return {pages,errors};
}
async function capture(p:Page){await p.bringToFront();const s=await read(p);if(s.inventoryOpen)await p.keyboard.press('Tab');if((await read(p)).paused)await p.locator('#resume').press('Enter');else if(!s.camera.pointerLocked)await p.locator('#capture-mouse').press('Enter');await p.waitForFunction(()=>!!document.pointerLockElement);}
async function position(p:Page,x:number,z:number,yaw=Math.PI,pitch=0){await p.evaluate(v=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(v.x,v.z);g.setLook(v.yaw,v.pitch);},{x,z,yaw,pitch});await expect.poll(async()=>{const s=await read(p),a=s.coop.players.find((a:any)=>a.actor===s.coop.actor);return Math.hypot(a.player.x-x,a.player.z-z);}).toBeLessThan(.2);}
async function fire(p:Page){await capture(p);await p.evaluate(()=>document.querySelector('canvas')!.dispatchEvent(new PointerEvent('pointerdown',{button:0,bubbles:true})));await p.waitForTimeout(160);await p.evaluate(()=>window.dispatchEvent(new PointerEvent('pointerup',{button:0,bubbles:true})));await p.waitForTimeout(650);}
async function spawn(a:Page,x:number,z:number,kind='walker',hp?:number){return a.evaluate(({x,z,kind,hp})=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const e=w.sim.spawn({x,z},kind);e.speedFactor=0;if(hp)e.hp=hp;return e.id;},{x,z,kind,hp});}
const local=(s:any)=>s.coop.players.find((a:any)=>a.actor===s.coop.actor);
async function agreed(pages:Page[],id:number,hp:number){for(const p of pages)await expect.poll(async()=>(await read(p)).zombies.find((z:any)=>z.id===id)?.hp??0).toBe(hp);}
async function health(pages:Page[],actor:number,life:string,hp?:number){for(const p of pages){await expect.poll(async()=>(await read(p)).coop.players.find((a:any)=>a.actor===actor)?.life).toBe(life);if(hp!==undefined)await expect.poll(async()=>(await read(p)).coop.players.find((a:any)=>a.actor===actor)?.player.hp).toBe(hp);}}
async function evidence(pages:Page[],name:string,errors:string[]){const rows=await Promise.all(pages.map(read));await writeFile(`${evidenceDir}/${name}.json`,JSON.stringify({renderer:await renderer(pages[0]),clients:rows.map((s,i)=>({wire:wire.get(pages[i]),coop:s.coop,network:s.network,fps:s.fps,calls:s.calls,triangles:s.triangles,audio:s.audio})),errors},null,2));await pages[0].screenshot({path:`${evidenceDir}/${name}.png`,scale:'css'});expect(errors).toEqual([]);}

test('two real Photon clients: combat, loot race, doors and persistent master migration',async({browser})=>{
 const {pages,errors}=await room(browser,2),[a,b]=pages;try{
 await position(a,88,-30,Math.PI,-.10);await position(b,88,-30,Math.PI,-.10);const id=await spawn(a,88,-35);await agreed(pages,id,90);
 await fire(a);await expect.poll(async()=>(await read(b)).zombies.find((z:any)=>z.id===id)?.hp).toBeLessThan(90);const first=(await read(b)).zombies.find((z:any)=>z.id===id).hp;console.log('A fire replicated',first);
 await fire(b);await expect.poll(async()=>(await read(a)).zombies.find((z:any)=>z.id===id)?.hp??0).toBeLessThan(first);console.log('B fire replicated');
 await position(a,88,-30,Math.PI,.015);await fire(a);await agreed(pages,id,0);for(const p of pages){await expect.poll(async()=>(await read(p)).coop.confirmed.filter((e:any)=>e.event.type==='death'&&e.event.entity===id).length).toBe(1);expect((await read(p)).corpses.some((c:any)=>c.id===id)).toBe(true);expect((await read(p)).coop.confirmed.find((e:any)=>e.event.type==='death'&&e.event.entity===id).event.zone).toBe('HEAD');}console.log('shared death + corpse');
 await capture(a);await a.keyboard.press('Tab');await expect.poll(async()=>(await read(a)).inventoryOpen).toBe(true);await a.screenshot({path:`${evidenceDir}/inventory.png`});await a.keyboard.press('Tab');
 // Race on the same initial ammo box, through the real E binding.
 const l=(await read(a)).loot.find((l:any)=>l.id==='base-ammo');for(const p of pages){await capture(p);await position(p,l.x,l.z+1.6,Math.PI,-.60);await expect.poll(async()=>(await read(p)).focus?.id).toBe(l.id);}
 const reserves=(await Promise.all(pages.map(read))).map(s=>local(s).inventory.ammo);
 // No focus switching between the two events: dispatch uses the same input event listeners as E.
 await Promise.all(pages.map(p=>p.evaluate(()=>{window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyE',key:'e',bubbles:true}));window.dispatchEvent(new KeyboardEvent('keyup',{code:'KeyE',key:'e',bubbles:true}));})));
 await expect.poll(async()=>(await read(a)).loot.find((l:any)=>l.id==='base-ammo').searched).toBe(true);
 await expect.poll(async()=>(await read(a)).loot.find((l:any)=>l.id==='base-ammo').contents.ammo).toBe(0);
 await expect.poll(async()=>(await Promise.all(pages.map(read))).reduce((sum,s,i)=>sum+local(s).inventory.ammo-reserves[i],0)).toBe(36);
 const gains=(await Promise.all(pages.map(read))).map((s,i)=>local(s).inventory.ammo-reserves[i]);expect(gains.reduce((a,b)=>a+b,0)).toBe(36);expect(gains.filter(n=>n>0)).toHaveLength(1);expect(new Set((await read(a)).coop.confirmed.filter((e:any)=>e.event.type==='search').map((e:any)=>e.actor)).size).toBe(2);console.log('loot race one winner',gains);
 for(const p of pages)await position(p,112,-97,Math.PI,-.08);await capture(a);await expect.poll(async()=>(await read(a)).focus?.id).toBe('hospital-main-front');await a.keyboard.press('e');for(const p of pages)await expect.poll(async()=>(await read(p)).portals.find((d:any)=>d.id==='hospital-main-front').state).toBe('open');await capture(b);await b.keyboard.press('e');for(const p of pages)await expect.poll(async()=>(await read(p)).portals.find((d:any)=>d.id==='hospital-main-front').state).toBe('closed');await b.waitForTimeout(300);await b.keyboard.press('e');await expect.poll(async()=>(await read(a)).portals.find((d:any)=>d.id==='hospital-main-front').state).toBe('open');
 const partial=await spawn(a,90,-35,'walker',37);const actorB=(await read(b)).coop.actor;await a.evaluate(actor=>{const w=(window as any).__LAST_NIGHT__.coopFixture();w.damage(actor,20);},actorB);await health(pages,actorB,'alive',80);await agreed(pages,partial,37);await evidence(pages,'two-combat-before-migration',errors);
 await capture(a);await a.keyboard.press('Escape');await a.locator('#pause-menu').click();await expect.poll(async()=>(await read(b)).coop.master).toBe(actorB);await expect.poll(async()=>(await read(b)).coop.migrations).toBe(1);const migrated=await read(b);expect(migrated.zombies.find((z:any)=>z.id===partial).hp).toBe(37);expect(migrated.zombies.some((z:any)=>z.id===id)).toBe(false);expect(local(migrated).player.hp).toBe(80);expect(migrated.loot.find((l:any)=>l.id==='base-ammo').contents.ammo).toBe(0);expect(migrated.portals.find((d:any)=>d.id==='hospital-main-front').state).toBe('open');
 await position(b,90,-30,Math.PI,.015);await fire(b);await agreed([b],partial,0);await evidence([b],'migration-continued',errors);
 }finally{for(const p of pages)await p.context().close();}
});

for(const count of [3,4])test(`${count} real Photon clients: shared shotgun, attacks, downed/revive, loot and wipe`,async({browser})=>{
 const {pages,errors}=await room(browser,count),[a,b]=pages;try{
 for(let i=0;i<pages.length;i++)await position(pages[i],88+i*1.2,-30,Math.PI,-.12);
 // Give the coordinator's actor a real ground weapon; pick it up with E.
 await a.evaluate(()=>{const w=(window as any).__LAST_NIGHT__.coopFixture();w.sim.dropWeapon('shotgun',{x:88,z:-32},'common');});await capture(a);await position(a,88,-30,Math.PI,-.68);await expect.poll(async()=>(await read(a)).focus?.kind).toBe('weapon');await a.keyboard.press('e');await expect.poll(async()=>(await read(a)).weapon.type).toBe('shotgun');await expect.poll(async()=>(await read(a)).switchTimer).toBe(0);await position(a,88,-30,Math.PI,-.12);
 const id=await spawn(a,88,-33,'tank');await agreed(pages,id,310);await fire(a);const after=(await read(a)).zombies.find((z:any)=>z.id===id)?.hp??0;expect(after).toBeLessThan(310);await agreed(pages,id,after);const actorA=(await read(a)).coop.actor;for(const p of pages)expect((await read(p)).coop.players.find((r:any)=>r.actor===actorA).loadout[0].type).toBe('shotgun');
 for(const p of pages.slice(1)){await position(p,88,-30,Math.PI,.12);await fire(p);}console.log(`${count} clients fired`);
 // Clear the encounter, then a genuine Runner melee attack downs B.
 await a.evaluate(()=>{const w=(window as any).__LAST_NIGHT__.coopFixture();w.sim.zombies=[];});await position(a,90,-30);await position(b,88,-30);const actorB=(await read(b)).coop.actor;await a.evaluate(actor=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const p=w.actors.get(actor).sim.player;p.hp=7;p.invulnerable=0;w.sim.spawn({x:88,z:-30.8},'runner');},actorB);await health(pages,actorB,'downed',0);await expect(b.locator('#coop-revive')).toContainText('Você caiu');await a.evaluate(()=>{(window as any).__LAST_NIGHT__.coopFixture().sim.zombies=[];});
 await capture(a);await a.keyboard.down('e');await expect.poll(async()=>local(await read(a)).reviveProgress).toBeGreaterThan(.2);await position(a,95,-30);await expect.poll(async()=>local(await read(a)).reviveProgress).toBe(0);await a.keyboard.up('e');await position(a,90,-30);await a.keyboard.down('e');await health(pages,actorB,'alive',40);await a.keyboard.up('e');await evidence(pages,`${count}-players-revive`,errors);
 await position(a,88,-30,Math.PI,-.1);await position(b,102,-30,Math.PI,0);await fire(a);await expect.poll(async()=>(await read(b)).audio.lastRemoteShot?.weapon).toBe('shotgun');const remoteSound=(await read(b)).audio.lastRemoteShot;expect(Math.abs(remoteSound.pan)).toBeGreaterThan(.5);expect(remoteSound.attenuation).toBeLessThan(.6);
 // Every member sees the same one-time pickup and individual inventory mutation.
 const l=(await read(a)).loot.find((l:any)=>l.id==='base-ammo');await capture(b);await position(b,l.x,l.z+1.6,Math.PI,-.60);await expect.poll(async()=>(await read(b)).focus?.id).toBe(l.id);await b.keyboard.press('e');for(const p of pages){await expect.poll(async()=>(await read(p)).loot.find((l:any)=>l.id==='base-ammo').searched).toBe(true);await expect.poll(async()=>(await read(p)).loot.find((l:any)=>l.id==='base-ammo').contents.ammo).toBe(0);}
 // Bleedout uses the real 45-second timer; owner tick keeps running without focus.
 await a.evaluate(actor=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const p=w.actors.get(actor).sim.player;p.invulnerable=0;w.damage(actor,1000);},actorB);await health(pages,actorB,'downed',0);await expect.poll(async()=>(await read(a)).coop.players.find((p:any)=>p.actor===actorB).life,{timeout:65000}).toBe('dead');await health(pages,actorB,'dead',0);
 await a.evaluate(()=>{const w=(window as any).__LAST_NIGHT__.coopFixture();for(const p of w.actors.values()){p.sim.player.invulnerable=0;w.damage(p.actor,1000);}});for(const p of pages){await expect.poll(async()=>(await read(p)).gameOver).toBe(true);await expect(p.locator('#game-over')).toBeVisible();}await evidence(pages,`${count}-players-wipe`,errors);
 }finally{for(const p of pages)await p.context().close();}
});

test('four real Photon clients: bounded infected stress and measured traffic',async({browser})=>{
 const {pages,errors}=await room(browser,4),[a]=pages;const samples=[];try{
 for(let i=0;i<4;i++)await position(pages[i],88+i*1.2,-30,Math.PI,-.08);
 const cdp=await Promise.all(pages.map(p=>p.context().newCDPSession(p)));for(const session of cdp)await session.send('Performance.enable');
 const taskDuration=async()=>Promise.all(cdp.map(async session=>(await session.send('Performance.getMetrics')).metrics.find(m=>m.name==='TaskDuration')!.value));
 for(const requested of [10,25,50,100]){
 const actual=await a.evaluate(async requested=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const {collides}=await import('/src/game/world.ts');w.sim.zombies=[];w.sim.corpses.bodies=[];for(const a of w.actors.values())a.sim.player.invulnerable=99;for(let i=0;i<300&&w.sim.activeWalkers<requested;i++){const p={x:76+i%15*1.8,z:-45+Math.floor(i/15)*1.8};if(!collides(p,.6,w.sim.solidDefenses))w.sim.spawn(p,['walker','walker','runner','spitter','tank'][i%5]);if(w.sim.activeWalkers===40)break;}return w.sim.activeWalkers;},requested);
 for(const p of pages)await expect.poll(async()=>(await read(p)).zombies.length).toBe(actual);
 const cpuBefore=await taskDuration();const start=Date.now(),before=pages.map(p=>({...wire.get(p)!}));await a.waitForTimeout(3500);const states=await Promise.all(pages.map(read));const seconds=(Date.now()-start)/1000,cpuAfter=await taskDuration();
 samples.push({requested,actual,seconds,clients:states.map((s,i)=>({actor:s.coop.actor,rendererTaskCpuMsPerSecond:(cpuAfter[i]-cpuBefore[i])*1000/seconds,wssFrameIntervals:jitter(wire.get(pages[i])!.receivedAt,start),fps:s.fps,calls:s.calls,triangles:s.triangles,ping:s.network.metrics.ping,snapshotAgeMs:s.coop.snapshotAge,sendEventsPerSecond:s.network.metrics.sendRate,receiveEventsPerSecond:s.network.metrics.receiveRate,webSocketTxBytesPerSecond:(wire.get(pages[i])!.tx-before[i].tx)/seconds,webSocketRxBytesPerSecond:(wire.get(pages[i])!.rx-before[i].rx)/seconds,infected:s.zombies.length}))});console.log('stress',requested,'actual',actual);
 }
 await writeFile(`${evidenceDir}/stress-photon.json`,JSON.stringify({renderer:await renderer(a),quality:'low',viewport:'960x640',scale:process.env.LAST_NIGHT_GPU==='1'?1:.5,transport:'Observed frames on real Photon WSS; includes Photon framing, excludes TLS/TCP/IP overhead. Existing 40 living infected cap preserved. Interval standard deviation measures arrival variability of all WSS frame types, including browser scheduling, not isolated network latency. CPU is CDP renderer TaskDuration, excludes GPU.',samples,errors},null,2));expect(errors).toEqual([]);
 }finally{for(const p of pages)await p.context().close();}
});

test('solo remains playable offline: combat, inventory, loot, door, night and immediate death',async({browser})=>{
 const context=await browser.newContext({viewport:{width:960,height:640},deviceScaleFactor:process.env.LAST_NIGHT_GPU==='1'?1:.5});const p=await context.newPage();p.setDefaultTimeout(45000);const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));try{
 await p.addInitScript(()=>localStorage.setItem('last-night-settings',JSON.stringify({quality:'low',shadows:false,master:0})));await p.goto('/?test',{waitUntil:'domcontentloaded'});await p.locator('#start').click();await p.waitForFunction(()=>!!document.pointerLockElement);await context.setOffline(true);
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(88,-30);g.setLook(Math.PI,.015);g.spawn(88,-34);g.setAmmo(12);});for(let i=0;i<3;i++){await p.evaluate(()=>document.querySelector('canvas')!.dispatchEvent(new PointerEvent('pointerdown',{button:0,bubbles:true})));await p.waitForTimeout(200);await p.evaluate(()=>window.dispatchEvent(new PointerEvent('pointerup',{button:0,bubbles:true})));await p.waitForTimeout(400);}await expect.poll(async()=>(await read(p)).kills).toBeGreaterThan(0);
 await p.keyboard.press('Tab');await expect.poll(async()=>(await read(p)).inventoryOpen).toBe(true);await p.keyboard.press('Tab');const l=(await read(p)).loot.find((l:any)=>l.id==='base-ammo');await p.evaluate(l=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(l.x,l.z+1.6);g.setLook(Math.PI,-.6);},l);await expect.poll(async()=>(await read(p)).focus?.id).toBe(l.id);await p.keyboard.press('e');await expect.poll(async()=>(await read(p)).loot.find((l:any)=>l.id==='base-ammo').searched).toBe(true);
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(112,-97);g.setLook(Math.PI,-.08);});await expect.poll(async()=>(await read(p)).focus?.id).toBe('hospital-main-front');await p.keyboard.press('e');await expect.poll(async()=>(await read(p)).portals.find((d:any)=>d.id==='hospital-main-front').state).toBe('open');await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPhase('night');g.setHealth(0);});await expect(p.locator('#game-over')).toBeVisible();expect((await read(p)).coop).toBeUndefined();expect((await read(p)).network.state).toBe('disconnected');expect(errors).toEqual([]);await mkdir(evidenceDir,{recursive:true});await writeFile(`${evidenceDir}/solo-offline.json`,JSON.stringify({checks:['combat/death','Tab inventory','ammo search','door','night phase','immediate solo death'],network:'offline after page loaded',errors},null,2));
 }finally{await context.close();}
});

test('two real Photon clients: visible downed body, revive HUD cleanup and remote world weapon',async({browser})=>{
 const {pages,errors}=await room(browser,2),[a,b]=pages;try{
 await capture(a);await position(a,90,-30,-Math.PI/2,-.32);await position(b,88,-30,Math.PI,0);const actorB=(await read(b)).coop.actor;
 await a.evaluate(actor=>{const w=(window as any).__LAST_NIGHT__.coopFixture();w.damage(actor,1000);},actorB);await health(pages,actorB,'downed',0);await expect(a.locator('#coop-revive')).toContainText('REVIVER');await a.screenshot({path:`${evidenceDir}/downed-body.png`});
 await a.keyboard.down('e');await health(pages,actorB,'alive',40);await a.keyboard.up('e');await expect(a.locator('#coop-revive')).toBeHidden();await a.waitForTimeout(150);await expect(a.locator('#coop-revive')).toBeHidden();
 await a.evaluate(async actor=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const {createWeapon}=await import('/src/game/weapons.ts');const s=w.actors.get(actor).sim;s.loadout[0]=createWeapon('shotgun',w.sim.nextWeaponId++);s.activeSlot=0;},actorB);await expect.poll(async()=>(await read(a)).coop.players.find((p:any)=>p.actor===actorB).loadout[0]?.type).toBe('shotgun');await position(a,90,-30,-Math.PI/2,0);await a.waitForTimeout(300);await a.screenshot({path:`${evidenceDir}/revived-world-weapon.png`});await writeFile(`${evidenceDir}/visual-coop.json`,JSON.stringify({renderer:await renderer(a),checks:['downed body visible','E revive to 40 HP','revive prompt remains hidden after completion','remote shotgun model'],errors},null,2));expect(errors).toEqual([]);
 }finally{for(const p of pages)await p.context().close();}
});
