import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CoopWorld} from '../src/network/coop-world.ts';
import {parseCheckpoint,stateHash} from '../src/network/checkpoint.ts';
import {createPatch,applyPatch} from '../src/network/world-patch.ts';
import {entityId,validEntityId,NetworkEntityRegistry} from '../src/network/entities.ts';
import {parseAction,shotSeed,COOP,poseOf} from '../src/network/gameplay-protocol.ts';
import type {ActionRequest} from '../src/network/gameplay-protocol.ts';
import {floorHeight} from '../src/game/world.ts';
import {createWeapon} from '../src/game/weapons.ts';
import {interactionFocus} from '../src/game/interaction.ts';
const world=()=>{const w=new CoopWorld(1977,[1,2]);w.sim.zombies=[];w.sim.activatedSites=new Set(['hospital','market']);return w;};
const step=(w:CoopWorld,seconds:number)=>{for(let i=0;i<Math.ceil(seconds*60);i++)w.step(1/60);};
function pose(w:CoopWorld,actor:number,x:number,z:number,yaw=Math.PI,pitch=0){const p=w.actors.get(actor)!.sim.player;const result=poseOf({...p,x,z,angle:yaw,pitch},floorHeight({x,z}),w.time*1000);w.setPose(actor,result);return result;}
function fire(w:CoopWorld,actor:number,shot:number){const a=w.actors.get(actor)!;return w.request(actor,{kind:'fire',seq:a.lastSeq+1,shot,seed:shotSeed(actor,shot),weapon:a.sim.equipped.type,ads:false,bloom:0,kick:0,pose:poseOf(a.sim.player,floorHeight(a.sim.player),w.time*1000)});}
function lootPose(w:CoopWorld,actor:number,id:string){const l=w.sim.loot.find(l=>l.id===id)!;const p=pose(w,actor,l.x,l.z+1.6,Math.PI,Math.atan2(.65-(floorHeight(l)+1.72),1.6));assert.equal(interactionFocus(w.actors.get(actor)!.sim)?.id,id);return p;}
test('entity identities and registry reject duplicate/invalid IDs',()=>{assert.equal(entityId('infected',10),'infected:10');assert.ok(validEntityId('door:home-4-front'));assert.ok(!validEntityId('bad:1'));assert.throws(()=>entityId('container','<script>'));const r=new NetworkEntityRegistry<object>();const id=entityId('player',1);r.register(id,{});assert.throws(()=>r.register(id,{}));assert.equal(r.size,1);assert.ok(r.remove(id));assert.equal(r.get(id),undefined);});
test('request validation rejects forged fields, NaN, invalid weapon, huge seq and replay',()=>{const w=world();const p=pose(w,1,88,-30);const good={kind:'fire',seq:1,shot:1,seed:shotSeed(1,1),weapon:'pistol',ads:false,bloom:0,kick:0,pose:p};assert.ok(parseAction(good));for(const bad of [{...good,weapon:'rocket'},{...good,seq:Infinity},{...good,pose:{...p,x:NaN}},{...good,pose:{...p,x:1000}},{...good,seed:-1},{kind:'damage',damage:999999},null])assert.equal(parseAction(bad),null);assert.ok(w.request(1,good as ActionRequest));assert.ok(!w.request(1,good as ActionRequest));assert.ok(!w.request(99,good as ActionRequest));});
test('shared hitscan preserves headshot, cadence, ammunition, death once and one drop',()=>{const w=world();pose(w,1,88,-30,Math.PI,Math.atan2(1.89-(floorHeight({x:88,z:-30})+1.72),5));pose(w,2,100,-30);const z=w.sim.spawn({x:88,z:-35})!;assert.ok(z);assert.ok(fire(w,1,1));const hp=z.hp;assert.ok(hp<90);assert.equal(z.zone,'HEAD');assert.equal(w.actors.get(1)!.sim.ammo,11);assert.ok(!fire(w,1,2));assert.equal(z.hp,hp);step(w,.3);assert.ok(fire(w,1,3));assert.equal(z.active,false);const count=w.sim.corpses.bodies.length;step(w,.3);fire(w,1,4);assert.equal(w.sim.corpses.bodies.length,count);assert.equal(w.sim.loot.filter(l=>l.id===`infected-${z.id}`).length,1);assert.equal(w.effects.filter(e=>e.event.type==='death').length,1);});
test('shotgun retains eight pellets, one ammo debit and shell reload interruption',()=>{const w=world(),a=w.actors.get(1)!;a.sim.loadout[0]=createWeapon('shotgun',100);a.sim.activeSlot=0;a.sim.inventory.items.shells=6;pose(w,1,88,-30,Math.PI,-.08);pose(w,2,100,-30);w.sim.spawn({x:88,z:-33},'tank');assert.ok(fire(w,1,1));assert.equal(a.sim.ammo,5);assert.equal(w.effects.filter(e=>e.event.type==='shot').length,8);step(w,1);a.sim.ammo=1;a.sim.reload();assert.ok(a.sim.reloadTimer);assert.ok(fire(w,1,2));assert.equal(a.sim.reloadTimer,0);assert.equal(a.sim.ammo,0);assert.ok(!fire(w,1,3));});
test('pickup race grants shared ammo once and inventory stays individual',()=>{const w=world();const id='police-locker';w.sim.loot.find(l=>l.id===id)!.area='base';for(const actor of [1,2]){const p=lootPose(w,actor,id);const a=w.actors.get(actor)!;assert.ok(w.request(actor,{kind:'interact',seq:a.lastSeq+1,target:entityId('container',id),pose:p}));}const start=[...w.actors.values()].map(a=>a.sim.reserve);step(w,1.5);const gains=[...w.actors.values()].map((a,i)=>a.sim.reserve-start[i]);assert.equal(gains[0]+gains[1],24);assert.equal(gains.filter(g=>g>0).length,1);assert.equal(w.sim.loot.find(l=>l.id===id)!.contents.ammo,0);assert.ok(w.effects.some(e=>e.event.type==='notice'&&e.event.text==='Já recolhido'));});
test('HP, downed, interrupted revive, unique completion and invulnerability',()=>{const w=world();pose(w,1,88,-30);pose(w,2,89,-30);w.damage(2,200);assert.equal(w.actors.get(2)!.life,'downed');assert.equal(w.actors.get(2)!.sim.player.hp,0);assert.ok(!fire(w,2,1));const hold=()=>{const a=w.actors.get(1)!;w.request(1,{kind:'hold',seq:a.lastSeq+1,target:2,held:true,pose:poseOf(a.sim.player,0,w.time*1000)});};hold();step(w,.2);assert.ok(w.actors.get(1)!.reviveProgress>0);pose(w,1,95,-30);step(w,.1);assert.equal(w.actors.get(1)!.reviveProgress,0);pose(w,1,88,-30);for(let i=0;i<44;i++){hold();step(w,.1);}assert.equal(w.actors.get(2)!.life,'alive');assert.equal(w.actors.get(2)!.sim.player.hp,COOP.reviveHP);assert.equal(w.effects.filter(e=>e.actor===2&&e.event.type==='healed').length,1);w.damage(2,10);assert.equal(w.actors.get(2)!.sim.player.hp,COOP.reviveHP);});
test('bleedout becomes dead and wipe does not force solo downed mechanics',()=>{const w=world();w.damage(2,1000);step(w,46);assert.equal(w.actors.get(2)!.life,'dead');assert.equal(w.wipe,false);w.damage(1,1000);step(w,.1);assert.equal(w.wipe,true);});
test('infected can target non-host and spitter damage is coordinator-owned',()=>{const w=world();pose(w,1,105,-30);pose(w,2,88,-30);const z=w.sim.spawn({x:88,z:-30.8},'runner')!;assert.ok(z);step(w,1.4);assert.ok(w.actors.get(2)!.sim.player.hp<100);assert.equal(w.actors.get(1)!.sim.player.hp,100);w.sim.zombies=[];w.sim.acids.push({id:w.sim.nextAcidId++,x:88,z:-30,from:{x:88,z:-35},age:0,tick:.7});const before=w.actors.get(2)!.sim.player.hp;step(w,1.5);assert.ok(w.actors.get(2)!.sim.player.hp<before);});
test('checkpoint round-trip and migration preserve damaged infected, loot, doors, ammo and HP',()=>{const w=world();pose(w,1,88,-30);pose(w,2,89,-30);const z=w.sim.spawn({x:88,z:-35})!;z.hp=37;const l=w.sim.loot[0];l.searched=true;l.contents.ammo=0;w.sim.portals[0].state='open';w.sim.portals[0].hp=0;w.damage(2,20);w.actors.get(2)!.sim.ammo=3;const c=w.checkpoint();assert.ok(parseCheckpoint(c));const migrated=CoopWorld.restore(1977,c,[2]);assert.equal(migrated.actors.size,1);assert.equal(migrated.sim.zombies.find(v=>v.id===z.id)!.hp,37);assert.equal(migrated.sim.loot[0].searched,true);assert.equal(migrated.sim.portals[0].state,'open');assert.equal(migrated.actors.get(2)!.sim.player.hp,80);assert.equal(migrated.actors.get(2)!.sim.ammo,3);step(migrated,.2);assert.ok(parseCheckpoint(migrated.checkpoint()));});
test('delta matches full state, wrong base and malformed state are rejected',()=>{const w=world(),a=w.checkpoint();w.damage(2,25);w.sim.loot[0].searched=true;const b=w.checkpoint(),patch=createPatch(a,b),applied=applyPatch(a,patch);assert.ok(applied);assert.equal(stateHash(applied),stateHash(b));assert.ok(JSON.stringify(patch).length<JSON.stringify(b).length/2);assert.equal(applyPatch(b,patch),null);for(const change of [{...b,players:[]},{...b,infected:[{id:0,hp:NaN}]},{...b,loot:[]},{...b,players:b.players.map(p=>({...p,inventory:{ammo:-1}}))},{...b,portals:[]}])assert.equal(parseCheckpoint(change),null);});
test('two rescuers complete only one revive; damage, release and disconnect cancel holds',()=>{const w=new CoopWorld(1977,[1,2,3]);w.sim.zombies=[];for(const [i,id] of [1,2,3].entries())pose(w,id,88+i*.6,-30);w.damage(2,200);const hold=(id:number,held=true)=>{const a=w.actors.get(id)!;w.request(id,{kind:'hold',seq:a.lastSeq+1,target:2,held,pose:poseOf(a.sim.player,0,w.time*1000)});};hold(1);step(w,.2);w.damage(1,10);assert.equal(w.actors.get(1)!.reviveTarget,0);hold(1);step(w,.2);hold(1,false);step(w,.1);assert.equal(w.actors.get(1)!.reviveProgress,0);for(let i=0;i<44;i++){hold(1);hold(3);step(w,.1);}assert.equal(w.effects.filter(e=>e.actor===2&&e.event.type==='healed').length,1);w.setMembers([2,3]);assert.equal(w.actors.has(1),false);});
test('facilities are shared, awarded once, and persist through migration without local alarms',()=>{const w=world();const f=w.sim.facilities.find(f=>f.id==='car-trunk')!;for(const id of [1,2]){const a=w.actors.get(id)!;const p=pose(w,id,f.x,f.z+1.7,Math.PI,-.4);a.sim.facilities=w.sim.facilities;assert.equal(interactionFocus(a.sim)?.id,f.id);assert.ok(w.request(id,{kind:'interact',seq:1,target:entityId('container',f.id),pose:p}));}step(w,2.2);assert.equal(f.state,'opened');assert.equal(w.effects.filter(e=>e.event.type==='notice'&&e.event.text==='RESERVA ABERTA').length,1);assert.equal(w.sim.alarmTimer,0);const c=w.checkpoint();assert.ok(parseCheckpoint(c));assert.equal(CoopWorld.restore(1977,c,[2]).sim.facilities.find(v=>v.id===f.id)!.state,'opened');});
test('shared doors handle simultaneous open and remote close without divergence',()=>{const w=world();const door=w.sim.portals.find(d=>d.kind==='door'&&d.state==='closed')!;for(const id of [1,2]){const a=w.actors.get(id)!;let found=false;for(const [dx,dz] of [[0,1.8],[0,-1.8],[1.8,0],[-1.8,0]]){const p=pose(w,id,door.x+dx,door.z+dz,Math.atan2(-dx,-dz),-.1);if(interactionFocus(a.sim)?.id!==door.id)continue;assert.ok(w.request(id,{kind:'interact',seq:1,target:entityId('door',door.id),pose:p}));found=true;break;}assert.ok(found);}step(w,.8);assert.equal(door.state,'open');const a=w.actors.get(2)!;assert.ok(w.request(2,{kind:'interact',seq:2,target:entityId('door',door.id),pose:poseOf(a.sim.player,0,w.time*1000)}));assert.equal(door.state,'closed');assert.ok(parseCheckpoint(w.checkpoint()));});
test('friendly fire is disabled; reload conserves magazine plus reserve; invalid state stays rejected',()=>{const w=world();pose(w,1,88,-30,Math.PI,-.1);pose(w,2,88,-32);assert.ok(fire(w,1,1));assert.equal(w.actors.get(2)!.sim.player.hp,100);const a=w.actors.get(1)!;const total=a.sim.ammo+a.sim.reserve;assert.ok(w.request(1,{kind:'reload',seq:2,pose:poseOf(a.sim.player,0,w.time*1000)}));assert.ok(!fire(w,1,2));step(w,2.6);assert.equal(a.sim.ammo+a.sim.reserve,total);assert.equal(a.sim.ammo,12);const c=w.checkpoint();for(const bad of [{...c,facilities:[]},{...c,players:c.players.map(p=>({...p,life:'downed',player:{...p.player,hp:100}}))}])assert.equal(parseCheckpoint(bad),null);});
test('presence-owned sprint cancels coordinator reload and attracts shared infected',()=>{const w=world();const a=w.actors.get(1)!;pose(w,1,88,-30);pose(w,2,105,-30);a.sim.ammo=1;a.sim.reload();const z=w.sim.spawn({x:88,z:-35})!;const p=poseOf({...a.sim.player,moving:true,running:true},0,100);w.setPose(1,p);step(w,.1);assert.equal(a.sim.reloadTimer,0);assert.ok(z.hearing>0);z.attack=-2001;assert.ok(parseCheckpoint(w.checkpoint()));});
test('Runner redirects from host to another survivor after position and noise change',()=>{const w=world();pose(w,1,88,-30);pose(w,2,105,-30);const z=w.sim.spawn({x:88,z:-36},'runner')!;step(w,.15);assert.ok(Math.abs(z.lastSeen!.x-88)<.1);pose(w,1,108,-30);pose(w,2,88,-30);assert.ok(fire(w,2,1));step(w,.15);assert.ok(Math.abs(z.lastSeen!.x-88)<.1);assert.ok(z.heard);assert.ok(z.hearing>0);assert.notEqual(z.lastSeen!.x,w.actors.get(1)!.sim.player.x);});
test('oversized, deeply nested and prototype-bearing action payloads are rejected',()=>{const w=world(),p=pose(w,1,88,-30);const r={kind:'reload',seq:1,pose:p};assert.ok(parseAction(r));assert.equal(parseAction({...r,extra:'x'.repeat(10000)}),null);assert.equal(parseAction({...r,extra:JSON.parse('{"__proto__":{"polluted":true}}')}),null);assert.equal(parseAction({...r,extra:Array.from({length:201},()=>1)}),null);});
