import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
async function pressMouse(p:Page,button:'left'|'right'='left'){await p.mouse.down({button});await p.mouse.up({button});}
async function aimBench(p:Page){await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__,s=g.state(),t=s.crafting.tables[0];g.setLook(Math.atan2(t.x-s.player.x,t.z-s.player.z),Math.atan2(t.y+1.2-s.player.eyeY,Math.hypot(t.x-s.player.x,t.z-s.player.z)));});}

const read=(p:Page)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
async function boot(p:Page){await p.addInitScript(()=>{
 localStorage.setItem('last-night-settings',JSON.stringify({quality:'medium',master:0}));
 // These scenarios aim with explicit fixtures. CDP emits delayed absolute motion
 // under Pointer Lock when changing buttons/tabs; suppress only that driver motion.
 // Native mousedown/up (including simultaneous RMB+LMB), keys and menus stay real.
 window.addEventListener('mousemove',e=>{if(document.pointerLockElement)e.stopImmediatePropagation();},true);
 });await p.goto('/?test');await expect(p.locator('#start')).toBeEnabled({timeout:90000});}
async function capture(p:Page){const s=await read(p);if(s.paused)await p.locator('#resume').click();if(!(await read(p)).camera.pointerLocked)await p.locator('#capture-mouse').click();await expect.poll(async()=>(await read(p)).camera.pointerLocked).toBe(true);}
test('solo crafting bench, armor, axe harvesting, fists and return beacon use real inventory controls',async({page:p})=>{
 const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewportSize({width:1600,height:900});await boot(p);await p.locator('#start').click();await expect(p.locator('#loading-screen')).toBeHidden({timeout:90000});await expect.poll(async()=>(await read(p)).camera.pointerLocked).toBe(true);
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setInventory({wood:12,scrap:15,hide:8,cloth:4,cord:3});g.setPlayer(1,7);g.setLook(Math.PI,0);});
 await p.keyboard.press('Tab');await expect(p.locator('#inventory-panel')).toBeVisible();await p.locator('#craft-tab').click();await expect(p.locator('#craft-details [data-craft]')).toHaveCount(1);await p.locator('[data-craft="bench"]').click();await expect.poll(async()=>(await read(p)).inventory.bench).toBe(1);await expect(p.locator('#place-bench')).toBeEnabled();await p.locator('#place-bench').click();await expect(p.locator('#inventory-panel')).toBeHidden();await expect(p.locator('#placement-help')).toBeVisible();await p.keyboard.down('a');await p.waitForTimeout(120);await p.keyboard.up('a');await p.keyboard.down('d');await p.waitForTimeout(120);await p.keyboard.up('d');await pressMouse(p);await expect.poll(async()=>(await read(p)).crafting.tables.length).toBe(1);
 await aimBench(p);await pressMouse(p,'right');await expect(p.locator('#workbench-screen')).toBeVisible();await p.locator('[data-recipe="axe"]').click();await p.locator('[data-craft="axe"]').click();await expect.poll(async()=>(await read(p)).gear.melee).toBe('axe');await p.locator('[data-recipe="leather"]').click();await p.locator('[data-craft="leather"]').click();await expect.poll(async()=>(await read(p)).gear.armor).toBe(80);
 await mkdir('test-results/crafting',{recursive:true});await p.screenshot({path:'test-results/crafting/craft-panel.png'});
 await p.keyboard.press('Tab');await capture(p);await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(8.8,2.8);g.setLook(Math.PI,0);});
 for(let i=0;i<3;i++){await expect.poll(async()=>(await read(p)).shotTimer).toBe(0);await pressMouse(p);await expect.poll(async()=>(await read(p)).crafting.trees.find((t:any)=>t.x===8.8&&t.z===1).hp).toBe(Math.max(0,100-42*(i+1)));}
 await p.screenshot({path:'test-results/crafting/axe-harvest.png'});
 await p.keyboard.press('4');await expect.poll(async()=>(await read(p)).activeSlot).toBe(3);await expect.poll(async()=>(await read(p)).switchTimer).toBe(0);
 const before=(await read(p)).loadout[1].magazine;await expect.poll(async()=>(await read(p)).shotTimer).toBe(0);await pressMouse(p);await expect.poll(async()=>(await read(p)).events.includes('melee')).toBe(true);expect((await read(p)).loadout[1].magazine).toBe(before);
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(1,18);g.setLook(Math.PI,0);g.setPhase('preparation',5);});await expect(p.locator('#return-base')).toBeVisible();await expect(p.locator('#base-marker')).toContainText('16 m');await p.screenshot({path:'test-results/crafting/return-beacon.png'});
 for(const viewport of [{width:1366,height:768},{width:1920,height:1080},{width:2560,height:1440}]){await p.setViewportSize(viewport);await p.keyboard.press('Tab');await expect(p.locator('#inventory-panel')).toBeVisible();await p.locator('#craft-tab').click();await expect(p.locator('#craft-details')).toBeVisible();const box=await p.locator('#inventory-panel').boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(viewport.width);await p.keyboard.press('Tab');}
 await p.keyboard.press('2');await expect.poll(async()=>(await read(p)).activeSlot).toBe(1);await expect.poll(async()=>(await read(p)).switchTimer).toBe(0);
 const rounds=(await read(p)).ammo;await p.mouse.down({button:'right'});await expect.poll(async()=>(await read(p)).player.ads).toBe(true);await pressMouse(p);await expect.poll(async()=>(await read(p)).ammo).toBe(rounds-1);await p.mouse.up({button:'right'});
 const state=await read(p);await writeFile('test-results/crafting/solo.json',JSON.stringify({errors,fps:state.fps,calls:state.calls,triangles:state.triangles,gear:state.gear,trees:state.crafting.trees.filter((t:any)=>!t.hp).length,quality:state.settings.quality},null,2));expect(errors).toEqual([]);
});
test('two Photon clients share crafting, tables, harvested trees, armor and migrating night state',async({browser})=>{
 const contexts=await Promise.all([browser.newContext(),browser.newContext()]);const pages=await Promise.all(contexts.map(c=>c.newPage()));const errors:string[]=[];
 for(const p of pages){p.on('pageerror',e=>errors.push(e.message));await boot(p);await p.locator('#coop-online').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});}
 const [a,b]=pages;await a.locator('#coop-create').click();await expect(a.locator('#coop-lobby')).toBeVisible();const code=await a.locator('#coop-room-code').innerText();await b.locator('#coop-code-input').fill(code);await b.locator('#coop-join').click();await expect(b.locator('#coop-lobby')).toBeVisible();await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await a.locator('#coop-start').click();
 for(const p of pages){await expect.poll(async()=>(await read(p)).network.state,{timeout:90000}).toBe('playing');await expect.poll(async()=>(await read(p)).coop?.revision??0).toBeGreaterThan(0);await expect(p.locator('#loading-screen')).toBeHidden({timeout:90000});}
 await a.evaluate(async()=>{const g=(window as any).__LAST_NIGHT__,w=g.coopFixture();const {CITY_SITES}=await import('/src/game/city.ts');w.sim.zombies=[];w.sim.activatedSites=new Set(CITY_SITES.map(s=>s.id));for(const a of w.actors.values()){Object.assign(a.sim.inventory.items,{wood:12,scrap:15,hide:8,cloth:4,cord:3});}g.setPlayer(1,7);g.setLook(Math.PI,0);});
 await expect.poll(async()=>(await read(a)).inventory.wood).toBe(12);await capture(a);await a.keyboard.press('Tab');await a.locator('#craft-tab').click();await a.locator('[data-craft="bench"]').click();await expect.poll(async()=>(await read(a)).inventory.bench).toBe(1);await a.locator('#place-bench').click();await expect(a.locator('#placement-help')).toBeVisible();await pressMouse(a);for(const p of pages)await expect.poll(async()=>(await read(p)).crafting.tables.length).toBe(1);
 await aimBench(a);await pressMouse(a,'right');await expect(a.locator('#workbench-screen')).toBeVisible();await a.locator('[data-recipe="axe"]').click();await a.locator('[data-craft="axe"]').click();await expect.poll(async()=>(await read(a)).gear.melee).toBe('axe');await a.locator('[data-recipe="leather"]').click();await a.locator('[data-craft="leather"]').click();await expect.poll(async()=>(await read(a)).gear.armor).toBe(80);
 await a.keyboard.press('Tab');await capture(a);await a.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(8.8,2.8);g.setLook(Math.PI,0);});
 await expect.poll(async()=>(await read(b)).network.remotes.some((r:any)=>r.snapshot&&Math.abs(r.snapshot.x-8.8)<.1)).toBe(true);
 for(let i=0;i<3;i++){await expect.poll(async()=>(await read(a)).shotTimer).toBe(0);await expect.poll(async()=>{const s=await read(a);return s.coop.players.find((r:any)=>r.actor===s.coop.actor).shotTimer;}).toBe(0);await pressMouse(a);for(const p of pages)await expect.poll(async()=>(await read(p)).crafting.trees.find((t:any)=>t.x===8.8&&t.z===1).hp).toBe(Math.max(0,100-42*(i+1)));}
 await a.evaluate(()=>{const w=(window as any).__LAST_NIGHT__.coopFixture();w.sim.setPhase('preparation',6);w.sim.baseHP=890;});await expect(b.locator('#return-base')).toBeVisible();const actorB=(await read(b)).coop.actor;
 await a.keyboard.press('Escape');await a.locator('#pause-menu').click();await expect.poll(async()=>(await read(b)).coop.master).toBe(actorB);await expect.poll(async()=>(await read(b)).coop.migrations).toBe(1);const state=await read(b);expect(state.crafting.tables.length).toBe(1);expect(state.baseHP).toBe(890);expect(state.crafting.trees.find((t:any)=>t.x===8.8&&t.z===1).hp).toBe(0);expect(state.phase).toBe('preparation');
 await b.screenshot({path:'test-results/crafting/coop-migration.png'});await writeFile('test-results/crafting/coop.json',JSON.stringify({errors,revision:state.coop.revision,migrations:state.coop.migrations,snapshotBytes:state.coop.snapshotBytes,phase:state.phase,baseHP:state.baseHP},null,2));expect(errors).toEqual([]);for(const c of contexts)await c.close();
});

test('workstation fortifications, traps, animated gate and distant districts remain playable',async({page:p})=>{
 const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewportSize({width:1600,height:900});await boot(p);await p.locator('#start').click();await expect(p.locator('#loading-screen')).toBeHidden({timeout:90000});await capture(p);
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(3.4,6.2);g.setLook(Math.PI,0);g.setInventory({wood:80,scrap:80,cloth:50,cord:20,bench:1});});
 await p.keyboard.press('Tab');await p.locator('#craft-tab').click();await p.locator('#place-bench').click();await expect.poll(async()=>(await read(p)).camera.pointerLocked).toBe(true);await pressMouse(p);await expect.poll(async()=>(await read(p)).crafting.tables.length).toBe(1);await aimBench(p);await pressMouse(p,'right');await expect(p.locator('#workbench-screen')).toBeVisible();
 // A slow real click must survive multiple HUD updates; do not replace its node.
 const target=p.locator('[data-recipe="axe"]');await target.evaluate(el=>{(window as any).__craftTarget=el;});await p.waitForTimeout(450);expect(await target.evaluate(el=>el===(window as any).__craftTarget)).toBe(true);await target.click({delay:450});await expect(p.locator('#bench-recipe h3')).toHaveText('Machado');
 for(const recipe of ['north','fortify-north','fortify-north','bed-gate','spikes-front','snare-west','wire-east']){await p.locator(`[data-recipe="${recipe}"]`).click();await p.locator(`[data-craft="${recipe}"]`).click();}
 expect((await read(p)).barricades.find((b:any)=>b.id==='north').hp).toBe(900);
 const light=(await read(p)).flashlight;await p.locator('#recipe-search').pressSequentially('mf');expect((await read(p)).mapOpen).toBe(false);expect((await read(p)).flashlight).toBe(light);await p.locator('#recipe-search').fill('arame');await expect(p.locator('#recipe-catalog [data-recipe]:visible')).toHaveCount(2);await p.locator('#recipe-search').fill('');
 for(const v of [{width:1366,height:768},{width:1920,height:1080},{width:2560,height:1440}]){await p.setViewportSize(v);const box=await p.locator('.workbench-window').boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(v.width);}
 await p.setViewportSize({width:1600,height:900});await mkdir('test-results/crafting',{recursive:true});await p.screenshot({path:'test-results/crafting/fortification-catalog.png'});await p.locator('#bench-close').click();await capture(p);
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(1,8);g.setLook(Math.PI,-.35);});await expect.poll(async()=>(await read(p)).focus?.id).toBe('bed-gate');await p.keyboard.press('e');await expect.poll(async()=>(await read(p)).barricades.find((b:any)=>b.id==='bed-gate').open).toBe(true);await p.waitForTimeout(500);await p.screenshot({path:'test-results/crafting/open-gate.png'});
 const scenes=[];for(const point of [{x:-468,z:-449,yaw:Math.PI},{x:468,z:447,yaw:0}]){await p.evaluate(point=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPhase('day');g.setPlayer(point.x,point.z);g.setLook(point.yaw,0);},point);await p.waitForTimeout(1500);const state=await read(p);scenes.push({x:point.x,z:point.z,fps:state.fps,calls:state.calls,triangles:state.triangles});await p.screenshot({path:`test-results/crafting/district-${point.x}.png`});}
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(468,452);g.setLook(0,0);for(const [i,kind]of ['armored','stalker','bloater'].entries())g.spawn(465+i*3,460,kind);});await p.waitForTimeout(400);await p.screenshot({path:'test-results/crafting/new-infected.png'});
 expect(errors).toEqual([]);await writeFile('test-results/crafting/expansion.json',JSON.stringify({errors,scenes,viewport:{width:1600,height:900},quality:'medium'},null,2));
});
