import {test,expect} from '@playwright/test';
import {writeFile,mkdir} from 'node:fs/promises';
for(const seed of [1,3])test(`seed ${seed}: walk to police, find and equip a real weapon, then return with the new loadout`,async({page})=>{
  test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('docs/variety',{recursive:true});await page.goto(`/?test&seed=${seed}`);await page.locator('#start').click();await page.keyboard.press('Escape');await page.locator('#quality').click();await page.locator('#resume').click();await page.addStyleTag({content:'#debug-stats{display:none}'});
  // Uses only observed state/path/project helpers and actual keyboard/pointer events.
  // No player teleport, equipment, enemies, health, resources, time or kill injection.
  await page.evaluate(()=>{
    const g=(window as any).__LAST_NIGHT__,canvas=document.querySelector('#game')!,run={stage:'outbound',keys:new Set<string>(),fire:false,path:[]as any[],replan:0,returnVia:0,acted:false,stop:false,found:null as any,initial:structuredClone(g.state()),result:null as any};(window as any).__expedition=run;
    const key=(code:string,down:boolean)=>window.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{code,bubbles:true}));const tap=(code:string)=>{key(code,true);key(code,false);};
    const keys=(desired:string[])=>{for(const k of run.keys)if(!desired.includes(k))key(k,false);for(const k of desired)if(!run.keys.has(k))key(k,true);run.keys=new Set(desired);};
    const fire=(value:boolean)=>{if(value&&run.fire&&g.state().shotTimer<=0&&!g.state().reloadTimer){canvas.dispatchEvent(new PointerEvent('pointerup',{button:0,bubbles:true}));run.fire=false;}if(value!==run.fire){canvas.dispatchEvent(new PointerEvent(value?'pointerdown':'pointerup',{button:0,bubbles:true}));run.fire=value;}};
    const travel=(s:any,to:{x:number;z:number})=>{if(Math.hypot(s.player.x-to.x,s.player.z-to.z)<.65){keys([]);return true;}if(performance.now()>run.replan||!run.path.length){run.path=g.pathTo(to.x,to.z);run.replan=performance.now()+700;}if(!run.path.length){run.stage='unreachable';run.stop=true;return false;}while(run.path.length>1&&Math.hypot(run.path[0].x-s.player.x,run.path[0].z-s.player.z)<.6)run.path.shift();const p=run.path[0],dx=p.x-s.player.x,dz=p.z-s.player.z,l=Math.hypot(dx,dz)||1,h=(dx-dz)/l,v=(dx+dz)/l;const desired=['ShiftLeft'];if(h>.35)desired.push('KeyD');else if(h<-.35)desired.push('KeyA');if(v>.35)desired.push('KeyS');else if(v<-.35)desired.push('KeyW');keys(desired);return false;};
    const tick=()=>{const s=g.state();if(run.stop||s.gameOver){keys([]);fire(false);run.stop=true;run.result=s;return;}
      if(s.action?.kind==='heal'||s.reloadTimer){keys([]);fire(false);requestAnimationFrame(tick);return;}
      if(s.player.hp<60&&s.inventory.med){keys([]);fire(false);tap('KeyH');requestAnimationFrame(tick);return;}
      if(!s.ammo&&s.reserve){keys([]);fire(false);tap('KeyR');requestAnimationFrame(tick);return;}
      let target=s.zombies.map((z:any)=>({...z,d:Math.hypot(z.x-s.player.x,z.z-s.player.z),screen:g.project(z.x,z.z)})).filter((z:any)=>z.d<22&&g.clearShot(z.x,z.z)&&z.screen.x>0&&z.screen.x<innerWidth&&z.screen.y>0&&z.screen.y<innerHeight).sort((a:any,b:any)=>a.d-b.d)[0];if(target)window.dispatchEvent(new PointerEvent('pointermove',{clientX:target.screen.x,clientY:target.screen.y,bubbles:true}));
      const loot=s.loot.find((l:any)=>l.id==='police-locker');
      if(run.stage==='outbound'){if(travel(s,{x:loot.x,z:loot.z+1.4})){run.stage='search';run.acted=false;}}
      else if(run.stage==='search'){keys([]);target=undefined;fire(false);if(!run.acted){tap('KeyE');run.acted=true;}if(loot.searched){run.found=s.groundWeapons[0]?.item;run.stage='equip';run.acted=false;}}
      else if(run.stage==='equip'){keys([]);target=undefined;fire(false);if(!run.acted){tap('KeyE');run.acted=true;}if(s.weapon.uid===run.found?.uid){run.stage='return';run.path=[];}}
      else if(run.stage==='return'){const route=[{x:16,z:18},{x:16,z:10},{x:1,z:10},{x:1,z:7}];if(travel(s,route[run.returnVia])){run.returnVia++;run.path=[];if(run.returnVia===route.length){run.stage='complete';run.stop=true;keys([]);fire(false);run.result=s;return;}}}
      fire(!!target&&run.stage!=='search'&&run.stage!=='equip');requestAnimationFrame(tick);
    };requestAnimationFrame(tick);
  });
  try{await page.waitForFunction(()=>(window as any).__expedition.stop,null,{timeout:210000});}finally{const diagnostic=await page.evaluate(()=>{const r=(window as any).__expedition;return {stage:r.stage,returnVia:r.returnVia,path:r.path,player:(window as any).__LAST_NIGHT__.state().player};});await writeFile(`docs/variety/expedition-seed-${seed}-route.json`,JSON.stringify(diagnostic,null,2));}const run=await page.evaluate(()=>{const r=(window as any).__expedition;return {stage:r.stage,found:r.found,initial:r.initial,result:r.result};});await writeFile(`docs/variety/expedition-seed-${seed}.json`,JSON.stringify(run,null,2));expect(run.stage).toBe('complete');expect(run.result.gameOver).toBe(false);expect(run.result.runSeed).toBe(seed);expect(run.result.stats.weapons).toBe(1);expect(run.result.weapon.type).toBe(seed===1?'marksman':'smg');expect(run.result.weapon.rarity).toBe(seed===1?'uncommon':'rare');await page.screenshot({path:`docs/variety/expedition-seed-${seed}.png`});expect(errors).toEqual([]);
});
test('acid is visible, escape avoids repeated damage and a headshot stops the spitter',async({page})=>{
  test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test');await page.locator('#start').click();await page.addStyleTag({content:'#debug-stats{display:none}'});await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPhase('dusk');g.spawn(1,14,'spitter');});
  await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().zombies.some((z:any)=>z.spitTarget),null,{timeout:20000});await page.screenshot({path:'docs/variety/spitter-telegraph.png'});
  await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().acids.some((a:any)=>a.age>=.7),null,{timeout:15000});await page.screenshot({path:'docs/variety/acid.png'});const before=await page.evaluate(()=>(window as any).__LAST_NIGHT__.state());await page.keyboard.down('d');try{await page.waitForFunction(p=>{const s=(window as any).__LAST_NIGHT__.state();return Math.hypot(s.player.x-p.x,s.player.z-p.z)>2.2;},before.player);}finally{await page.keyboard.up('d');}
  await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__,canvas=document.querySelector('#game')!;const tick=()=>{const s=g.state(),z=s.zombies.find((z:any)=>z.kind==='spitter');if(!z)return;if(z.spitTarget&&s.shotTimer<=0){const p=g.project(z.x-.07,z.z,1.87);window.dispatchEvent(new PointerEvent('pointermove',{clientX:p.x,clientY:p.y,bubbles:true}));canvas.dispatchEvent(new PointerEvent('pointerdown',{button:0,bubbles:true}));canvas.dispatchEvent(new PointerEvent('pointerup',{button:0,bubbles:true}));}requestAnimationFrame(tick);};requestAnimationFrame(tick);});
  await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().stats.specials===1,null,{timeout:25000});const final=await page.evaluate(()=>(window as any).__LAST_NIGHT__.state());expect(final.player.hp).toBeGreaterThan(60);expect(final.corpses.some((c:any)=>c.kind==='spitter')).toBe(true);await page.screenshot({path:'docs/variety/spitter-corpse.png'});expect(errors).toEqual([]);
});
