import {test,expect,type Browser,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const read=(p:Page)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
async function client(browser:Browser,name:string,deviceScaleFactor=.5){
 const context=await browser.newContext({viewport:{width:960,height:640},deviceScaleFactor});const p=await context.newPage();p.setDefaultTimeout(45000);
 await p.addInitScript(name=>{localStorage.setItem('last-night-settings',JSON.stringify({quality:'low',shadows:false,master:0}));localStorage.setItem('last-night-player-name',name);},name);
 await p.goto('http://127.0.0.1:5173/?test',{waitUntil:'domcontentloaded',timeout:90000});await p.locator('#coop-online').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});return p;
}
async function join(p:Page,code:string){await p.locator('#coop-code-input').fill(code);await p.locator('#coop-join').click();await expect(p.locator('#coop-lobby')).toBeVisible({timeout:60000});}
async function playing(p:Page){await expect.poll(async()=>(await read(p)).network.state,{timeout:60000}).toBe('playing');}
async function capture(p:Page){await p.bringToFront();if((await read(p)).paused)await p.locator('#resume').press('Enter');else await p.locator('#capture-mouse').press('Enter');await p.waitForFunction(()=>!!document.pointerLockElement);}
async function shot(p:Page,name:string){await p.screenshot({path:`docs/phase10a/${name}.png`,animations:'disabled',scale:'css'});}

test('real Photon: two clients, readiness, shared start, bidirectional motion and cleanup',async({browser})=>{
 await mkdir('docs/phase10a',{recursive:true});const errors:string[]=[];const a=await client(browser,'Pedro');a.on('pageerror',e=>errors.push(e.message));await shot(a,'create-room');await a.locator('#coop-create').click();await expect(a.locator('#coop-lobby')).toBeVisible();const code=await a.locator('#coop-room-code').innerText();console.log('Created',code);
 const b=await client(browser,'Amigo');b.on('pageerror',e=>errors.push(e.message));await b.locator('#coop-code-input').fill('000');await b.locator('#coop-join').click();await expect(b.locator('#coop-status')).toContainText('inválido');await shot(b,'invalid-code');await join(b,code);await expect(a.locator('#coop-players strong')).toHaveCount(2);await expect(a.locator('#coop-start')).toBeDisabled();await shot(a,'lobby-two');await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeDisabled();await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await shot(a,'host-ready');await a.locator('#coop-start').click();await playing(a);await playing(b);
 await expect.poll(async()=>(await read(a)).network.avatars).toBe(1);await expect.poll(async()=>(await read(b)).network.avatars).toBe(1);const initialA=await read(a),initialB=await read(b);expect(initialA.runSeed).toBe(initialB.runSeed);expect(Math.hypot(initialA.player.x-initialB.player.x,initialA.player.z-initialB.player.z)).toBeGreaterThan(2);await expect.poll(async()=>(await read(a)).coop?.infected??0).toBeGreaterThan(0);
 await capture(a);await a.keyboard.down('s');await a.waitForTimeout(1200);await a.keyboard.up('s');await expect.poll(async()=>Math.abs((await read(b)).network.remotes[0].snapshot.z-initialA.player.z)).toBeGreaterThan(1);console.log('A -> B movement passed');
 await capture(b);await b.keyboard.down('s');await b.keyboard.down('Shift');await expect.poll(async()=>(await read(a)).network.remotes[0].snapshot.locomotion).toBe(2);await b.waitForTimeout(700);await b.keyboard.up('s');await b.keyboard.up('Shift');await expect.poll(async()=>Math.abs((await read(a)).network.remotes[0].snapshot.z-initialB.player.z)).toBeGreaterThan(1);await b.keyboard.down('c');await expect.poll(async()=>(await read(a)).network.remotes[0].snapshot.locomotion).toBe(3);await b.keyboard.up('c');await b.mouse.move(400,280);await b.mouse.move(700,330);const turned=(await read(b)).player.angle;await expect.poll(async()=>Math.abs((await read(a)).network.remotes[0].snapshot.yaw-turned)).toBeLessThan(.1);console.log('B -> A, run, crouch, look passed');
 await b.keyboard.press('Escape');await expect(b.locator('#pause-screen')).toBeVisible();const received=(await read(b)).network.metrics.received;await b.waitForTimeout(1500);expect((await read(b)).network.metrics.received).toBeGreaterThan(received);await shot(b,'pause-online');
 await capture(a);await a.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;const s=g.state(),p=s.network.remotes[0].snapshot;g.setLook(Math.atan2(p.x-s.player.x,p.z-s.player.z),0);});await a.waitForTimeout(600);await shot(a,'gameplay-two');
 const metrics={a:await read(a),b:await read(b),errors};await writeFile('docs/phase10a/two-clients.json',JSON.stringify({region:metrics.a.network.region,seed:metrics.a.runSeed,a:metrics.a.network,b:metrics.b.network,renderA:{fps:metrics.a.fps,calls:metrics.a.calls,triangles:metrics.a.triangles},errors},null,2));expect(errors).toEqual([]);
 await a.keyboard.press('Escape');await a.locator('#pause-menu').click();await expect.poll(async()=>(await read(b)).network.players.length).toBe(1);await expect.poll(async()=>(await read(b)).network.players[0].isHost).toBe(true);await expect.poll(async()=>(await read(b)).network.avatars).toBe(0);expect((await read(a)).network.state).toBe('disconnected');await expect(a.locator('#coop-panel')).toBeHidden();
 await b.locator('#pause-menu').click();await expect(b.locator('#menu')).toBeVisible();await a.context().setOffline(true);await a.locator('#start').press('Enter');await expect(a.locator('#menu')).toBeHidden();expect((await read(a)).network.state).toBe('disconnected');await a.context().close();await b.context().close();
});

test('real Photon: four slots, fifth rejection, closed room, migration and refresh',async({browser})=>{
 const pages:Page[]=[];for(const name of ['Ana','Bruno','Carla','Davi','Eva']){pages.push(await client(browser,name));console.log('Connected',name);}const [a,b,c,d,e]=pages;
 await a.locator('#coop-create').click();await expect(a.locator('#coop-lobby')).toBeVisible();const code=await a.locator('#coop-room-code').innerText();await join(b,code);await join(c,code);await expect(a.locator('#coop-players strong')).toHaveCount(3);console.log('Three players in lobby');await shot(a,'lobby-three');await join(d,code);await expect(a.locator('#coop-players strong')).toHaveCount(4);console.log('Four players in lobby');await shot(a,'lobby-four');
 await e.locator('#coop-code-input').fill(code);await e.locator('#coop-join').click();await expect(e.locator('#coop-status')).toContainText('cheia',{timeout:60000});await shot(e,'room-full');
 await a.locator('#coop-close').click();await expect(b.locator('#coop-start')).toBeVisible();await expect.poll(async()=>(await read(b)).network.players.length).toBe(3);await a.locator('#coop-online').click();await expect(a.locator('#coop-create')).toBeEnabled({timeout:60000});await join(a,code);
 for(const p of [a,c,d])await p.locator('#coop-ready').click();await expect(b.locator('#coop-start')).toBeEnabled();await b.locator('#coop-start').click();for(const p of [a,b,c,d])await playing(p);await expect.poll(async()=>(await read(b)).network.avatars).toBe(3);console.log('Four players in game');
 await capture(b);await b.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(1,12);g.setLook(Math.PI,0);});await b.waitForTimeout(1000);await shot(b,'gameplay-four');await writeFile('docs/phase10a/four-clients.json',JSON.stringify(await Promise.all([a,b,c,d].map(async p=>{const s=await read(p);return {network:s.network,fps:s.fps,calls:s.calls,triangles:s.triangles,render:s.render};})),null,2));
 await d.reload({waitUntil:'domcontentloaded',timeout:90000});await expect.poll(async()=>(await read(b)).network.players.length).toBe(3);await expect.poll(async()=>(await read(b)).network.avatars).toBe(2);
 await e.locator('#coop-join').click();await expect(e.locator('#coop-status')).toContainText('fechada',{timeout:60000});await shot(e,'room-closed');

 for(const p of pages)await p.context().close();
});

test('real Photon transport with injected latency and ordered jitter',async({browser})=>{
 const a=await client(browser,'Latência A');await a.locator('#coop-create').click();await expect(a.locator('#coop-lobby')).toBeVisible();const code=await a.locator('#coop-room-code').innerText();
 const context=await browser.newContext({viewport:{width:800,height:500}});let delay=0,count=0;const timers=new Set<ReturnType<typeof setTimeout>>();let wireTx=0,wireRx=0;
 // Relay every frame to the real server; inject delay only, never fabricate a response.
 await context.routeWebSocket(/wss:\/\/.*(?:photonengine|exitgames)\./,ws=>{
  const server=ws.connectToServer();let nextTx=0,nextRx=0,closed=false;
  const later=(send:()=>void,out:boolean)=>{const now=Date.now(),jitter=[0,8,-6,12,-4][count++%5];const due=Math.max((out?nextTx:nextRx)+1,now+delay/2+jitter);if(out)nextTx=due;else nextRx=due;const t=setTimeout(()=>{timers.delete(t);if(!closed)send();},Math.max(0,due-now));timers.add(t);};
  ws.onMessage(message=>{wireTx+=typeof message==='string'?Buffer.byteLength(message):message.length;later(()=>server.send(message),true);});server.onMessage(message=>{wireRx+=typeof message==='string'?Buffer.byteLength(message):message.length;later(()=>ws.send(message),false);});ws.onClose(()=>{closed=true;server.close();});server.onClose(()=>{closed=true;ws.close();});
 });
 const b=await context.newPage();await b.addInitScript(()=>{localStorage.setItem('last-night-settings',JSON.stringify({quality:'low',shadows:false,master:0}));localStorage.setItem('last-night-player-name','Latência B');});await b.goto('http://127.0.0.1:5173/?test');await b.locator('#coop-online').click();await expect(b.locator('#coop-create')).toBeEnabled({timeout:60000});await join(b,code);await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await a.locator('#coop-start').click();await playing(a);await playing(b);await capture(b);
 const rows=[];for(const ms of [50,100,150,200]){delay=ms;const tx=wireTx,rx=wireRx,start=Date.now();await b.keyboard.down('c');await b.waitForTimeout(700);await expect.poll(async()=>(await read(a)).network.remotes[0].snapshot.locomotion).toBe(3);await b.keyboard.up('c');await b.keyboard.down('s');await b.waitForTimeout(700);await b.keyboard.up('s');await b.waitForTimeout(1000);const local=await read(b),remote=await read(a),other=remote.network.remotes[0].snapshot;expect(Math.hypot(other.x-local.player.x,other.z-local.player.z)).toBeLessThan(.3);expect(remote.network.buffers[0]).toBeLessThanOrEqual(32);rows.push({injectedRoundTripMs:ms,jitterMs:[-6,12],positionError:Math.hypot(other.x-local.player.x,other.z-local.player.z),rtt:local.network.metrics.ping,sendRate:local.network.metrics.sendRate,receiveRate:remote.network.metrics.receiveRate,buffer:remote.network.buffers[0],webSocketTxBytesPerSecond:(wireTx-tx)/(Date.now()-start)*1000,webSocketRxBytesPerSecond:(wireRx-rx)/(Date.now()-start)*1000});console.log('Latency passed',ms);}
 await writeFile('docs/phase10a/latency.json',JSON.stringify({transport:'Playwright frame relay to real Photon; ordered delay, no fabricated responses; byte counts include Photon JSON framing, exclude TLS/TCP/IP',rows},null,2));await context.close();for(const t of timers)clearTimeout(t);await a.context().close();
});

test('real Photon: deleted room, incompatible metadata, connection loss and responsive lobby',async({browser})=>{
 const p=await client(browser,'João da Luz',1);await p.locator('#coop-close').click();for(const [width,height] of [[1920,1080],[1600,900],[1366,768]]){await p.setViewportSize({width,height});await shot(p,`menu-${width}`);}
 await p.locator('#coop-online').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});await p.locator('#coop-create').click();await expect(p.locator('#coop-lobby')).toBeVisible();const deleted=await p.locator('#coop-room-code').innerText();for(const [width,height] of [[1920,1080],[1600,900],[1366,768]]){await p.setViewportSize({width,height});await expect(p.locator('#coop-start')).toBeInViewport();await expect(p.locator('#coop-leave')).toBeInViewport();await shot(p,`lobby-${width}`);}
 await p.locator('#coop-leave').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});await p.locator('#coop-code-input').fill(deleted);await p.locator('#coop-join').click();await expect(p.locator('#coop-status')).toContainText('não encontrada',{timeout:60000});await shot(p,'room-not-found');
 // Create a second genuine Photon client with deliberately incompatible room metadata.
 await p.evaluate(async()=>{const {NetworkManager}=await import('/src/network/manager.ts');const n=new NetworkManager();(window as any).__networkProbe=n;await n.connect('Protocol probe','sa');});await p.waitForFunction(()=>(window as any).__networkProbe.state==='connected');await p.evaluate(()=>(window as any).__networkProbe.create());await p.waitForFunction(()=>(window as any).__networkProbe.state==='lobby');const code=await p.evaluate(()=>{const n=(window as any).__networkProbe;n.client.myRoom().setCustomProperty('protocol',999);return n.code;});await p.waitForTimeout(500);await p.locator('#coop-code-input').fill(code);await p.locator('#coop-join').click();await expect(p.locator('#coop-status')).toContainText('outra versão',{timeout:60000});await shot(p,'incompatible-room');await p.evaluate(()=>(window as any).__networkProbe.dispose());
 await p.locator('#coop-retry').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});await p.locator('#coop-create').click();await expect(p.locator('#coop-lobby')).toBeVisible();await p.locator('#coop-start').click();await playing(p);await p.context().setOffline(true);await expect(p.locator('#coop-status')).toContainText(/conectar|perdida|conexão/i,{timeout:60000});await expect(p.locator('#coop-panel')).toBeVisible();expect((await read(p)).network.avatars).toBe(0);await shot(p,'connection-lost');await p.context().close();
});
