import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const state=(p:Page)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
const foods=['cannedBeans','cannedMeat','cannedFish','cannedFruit','crackers','ration','water','soda'];
async function prepare(p:Page,name='Sobrevivente'){await p.addInitScript(name=>{localStorage.setItem('last-night-settings',JSON.stringify({quality:'medium',master:0}));localStorage.setItem('last-night-player-name',name);window.addEventListener('mousemove',e=>{if(document.pointerLockElement)e.stopImmediatePropagation();},true);},name);await p.goto('/?test');await expect(p.locator('#start')).toBeEnabled({timeout:90000});}
async function capture(p:Page){await p.bringToFront();if((await state(p)).paused)await p.locator('#resume').press('Enter');else if(!(await state(p)).camera.pointerLocked)await p.locator('#capture-mouse').press('Enter');await expect.poll(async()=>(await state(p)).camera.pointerLocked).toBe(true);}
async function eat(p:Page,item:string){await capture(p);await p.keyboard.press('Tab');await p.locator('[data-supplies="food"]').click();await p.locator(`#select-${item}`).click();await expect(p.locator(`#consume-${item}`)).toBeEnabled();await p.locator(`#consume-${item}`).click();await expect.poll(async()=>(await state(p)).consumption?.item).toBe(item);}
test('solo: eight provisions, eat/drink animations, interruption, responsive inventory and firearm recovery',async({page:p})=>{
 const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));await prepare(p);await p.locator('#start').click();await expect(p.locator('#loading-screen')).toBeHidden({timeout:90000});await mkdir('docs/nutrition',{recursive:true});
 await p.evaluate(foods=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(1,12);g.setLook(0,0);g.setNutrition(30,25);g.setInventory(Object.fromEntries(foods.map(k=>[k,2])));},foods);
 await p.keyboard.press('Tab');await p.locator('[data-supplies="food"]').click();await p.locator('#select-cannedBeans').click();await expect.poll(()=>p.locator('.inventory-items img.food-art').evaluateAll(images=>images.length===8&&images.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true);
 for(const [width,height] of [[1366,768],[1920,1080],[960,640]]){await p.setViewportSize({width,height});await expect(p.locator('#consume-cannedBeans')).toBeInViewport({ratio:1});await expect(p.locator('.inventory-heading')).toBeInViewport({ratio:1});expect(await p.locator('#inventory-panel').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await p.screenshot({path:`docs/nutrition/inventory-${width}.png`});}
 await p.setViewportSize({width:1366,height:768});await p.keyboard.press('Tab');
 const outcomes=[];
 for(const item of foods){await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setNutrition(30,25);g.clearWalkers();});await eat(p,item);await expect.poll(async()=>(await state(p)).consumption?.elapsed??0,{intervals:[50,100]}).toBeGreaterThan(item==='water'||item==='soda'?1.15:1.6);await p.screenshot({path:`docs/nutrition/consume-${item}.png`});await expect.poll(async()=>(await state(p)).inventory[item]).toBe(1);await expect.poll(async()=>(await state(p)).consumption).toBe(null);outcomes.push({item,nutrition:(await state(p)).nutrition});}
 await p.evaluate(()=>{(window as any).__LAST_NIGHT__.setNutrition(20,20);});await eat(p,'water');await p.keyboard.down('w');await expect.poll(async()=>(await state(p)).consumption).toBe(null);await p.keyboard.up('w');expect((await state(p)).inventory.water).toBe(1);
 await capture(p);const ammo=(await state(p)).ammo;await p.mouse.down({button:'right'});await p.mouse.click(500,380);await p.mouse.up({button:'right'});await expect.poll(async()=>(await state(p)).ammo).toBe(ammo-1);await p.keyboard.down('Shift');await p.keyboard.down('w');await expect.poll(async()=>(await state(p)).player.running).toBe(true);await p.screenshot({path:'docs/nutrition/sprint.png'});await p.keyboard.up('w');await p.keyboard.up('Shift');
 await p.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(1,12);g.setHealth(100);g.setNutrition(20,20);});
 await expect.poll(async()=>(await state(p)).player.moving).toBe(false);await eat(p,'water');await p.evaluate(()=>{(window as any).__LAST_NIGHT__.spawn(1,12.8);});await expect.poll(async()=>(await state(p)).player.hp,{intervals:[50,100]}).toBeLessThan(100);await p.screenshot({path:'docs/nutrition/hurt.png'});await expect.poll(async()=>(await state(p)).consumption).toBe(null);expect((await state(p)).inventory.water).toBe(1);await p.evaluate(()=>(window as any).__LAST_NIGHT__.clearWalkers());
 expect(errors).toEqual([]);await writeFile('docs/nutrition/solo-validation.json',JSON.stringify({errors,foods:outcomes,resolutions:[[1366,768],[1920,1080],[960,640]],movementCancellation:true,damageCancellation:true,adsAfterFood:true},null,2));
});
for(const mode of ['photon','lan'] as const)test(`${mode}: authoritative eating, chest storage, interruption and needs survive host migration`,async({browser})=>{
 const contexts=await Promise.all([browser.newContext(),browser.newContext()]);const pages=await Promise.all(contexts.map(c=>c.newPage()));const [a,b]=pages,errors:string[]=[];
 try{
 for(const [i,p] of pages.entries()){p.on('pageerror',e=>errors.push(e.message));await prepare(p,`Food ${i+1}`);await p.locator('#coop-online').click();if(mode==='lan')await p.locator('#coop-transport').selectOption('lan');await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});}
 await a.locator('#coop-create').click();let code:string;
 if(mode==='lan'){await expect(a.locator('#loading-screen')).toBeHidden({timeout:90000});await capture(a);await a.keyboard.press('Escape');await a.locator('#pause-lan').click();await expect(a.locator('#pause-lan-code')).toBeVisible({timeout:45000});code=await a.locator('#pause-lan-code').inputValue();}else{await expect(a.locator('#coop-lobby')).toBeVisible();code=await a.locator('#coop-room-code').innerText();}
 await b.locator('#coop-code-input').fill(code);await b.locator('#coop-join').click();if(mode==='photon'){await expect(b.locator('#coop-lobby')).toBeVisible();await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await a.locator('#coop-start').click();}
 for(const p of pages)await expect.poll(async()=>(await state(p)).network.state,{timeout:90000}).toBe('playing');
 await a.evaluate(async()=>{const g=(window as any).__LAST_NIGHT__,w=g.coopFixture();const {CITY_SITES}=await import('/src/game/city.ts');w.sim.zombies=[];w.sim.spawnTimer=10000;w.sim.activatedSites=new Set(CITY_SITES.map(s=>s.id));for(const a of w.actors.values()){a.sim.nutrition.hunger=25;a.sim.nutrition.thirst=20;a.sim.inventory.items.cannedBeans=2;a.sim.inventory.items.water=2;a.sim.player.invulnerable=100;}});
 for(const p of pages)await expect.poll(async()=>(await state(p)).inventory.cannedBeans).toBe(2);
 await eat(b,'cannedBeans');await expect.poll(async()=>(await state(a)).coop.players.find((v:any)=>v.actor===(2))?.consumption?.item).toBe('cannedBeans');await expect.poll(async()=>(await state(b)).inventory.cannedBeans).toBe(1);expect((await state(b)).nutrition.hunger).toBeGreaterThan(49);expect((await state(a)).inventory.cannedBeans).toBe(2);
 await eat(b,'water');await b.keyboard.down('w');await expect.poll(async()=>(await state(b)).consumption).toBe(null);await b.keyboard.up('w');expect((await state(b)).inventory.water).toBe(2);
 // Transfer a provision via the same authoritative chest transaction used by the UI.
 await a.evaluate(async()=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const {placeChest,moveChest}=await import('/src/game/chests.ts');const s=w.actors.get(1).sim;Object.assign(s.player,{x:1,z:12,angle:0});s.inventory.items.chest=1;placeChest(s);const c=w.sim.crafting.chests[0];moveChest(s,{chest:c.id,revision:0,source:{bag:'water'},target:0,amount:1});});
 for(const p of pages)await expect.poll(async()=>(await state(p)).crafting.chests[0]?.slots[0]?.item).toBe('water');
 await capture(a);await a.keyboard.press('Escape');await a.locator('#pause-menu').click();await expect.poll(async()=>(await state(b)).coop.migrations,{timeout:15000}).toBe(1);expect((await state(b)).nutrition.hunger).toBeGreaterThan(48);expect((await state(b)).crafting.chests[0].slots[0]).toEqual({item:'water',amount:1});
 await eat(b,'water');await expect.poll(async()=>(await state(b)).inventory.water).toBe(1);expect((await state(b)).nutrition.thirst).toBeGreaterThan(60);expect(errors).toEqual([]);await b.screenshot({path:`docs/nutrition/${mode}.png`});
 }finally{for(const c of contexts)await c.close();}
});
