import {test,expect} from '@playwright/test';
import {writeFile,mkdir} from 'node:fs/promises';
const evidenceDir=process.env.PHASE9_EVIDENCE_DIR??'docs/phase9';
const state=(page:any)=>page.evaluate(()=>(window as any).__LAST_NIGHT__.state());
async function start(page:any){page.setDefaultTimeout(60000);await page.setViewportSize({width:1280,height:720});await page.addInitScript(()=>localStorage.setItem('last-night-settings',JSON.stringify({quality:'low',shadows:false})));await page.goto('/?test');await page.locator('#start').press('Enter');await page.waitForFunction(()=>!!document.pointerLockElement);await mkdir(evidenceDir,{recursive:true});}
test('Phase 9 furnished interiors, day/night contrast, radio, generator and horde metrics',async({page})=>{
 test.setTimeout(360000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);const rows:any[]=[];
 for(const [name,x,z] of [['house',-113,-65],['hospital',112,-105],['market',-113,70],['police',113,22],['industry',113,82],['church',-25,120],['terminal',62,107],['quarantine',114,135]] as const){
  await page.evaluate(({x,z})=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(x,z);g.setLook(Math.PI,0);g.setPhase('day');g.setHealth(1000);g.setBase(10000);},{x,z});await page.waitForTimeout(1600);await page.screenshot({animations:'disabled',path:`${evidenceDir}/interior-${name}-day.png`});
  const s=await state(page);rows.push({name,fps:s.fps,frameMs:1000/s.fps,calls:s.calls,triangles:s.triangles,entities:s.zombies.length,ai:s.zombies.length,audio:s.audio,render:s.render});
 }
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(112,-105);g.setLook(Math.PI,-.03);g.setPhase('night');g.spawn(1,16);});await page.waitForTimeout(1200);await page.screenshot({animations:'disabled',path:`${evidenceDir}/hospital-night.png`});await page.keyboard.press('f');await page.waitForTimeout(700);await page.screenshot({animations:'disabled',path:`${evidenceDir}/hospital-flashlight.png`});
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPhase('dusk');g.setPlayer(96,80);g.setLook(Math.PI,-.37);});await expect(page.locator('#interaction')).toContainText('ATIVAR GERADOR');await page.keyboard.press('e');await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().facilities.find((f:any)=>f.id==='foundry-power').state==='powered');await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().audio.generator);expect((await state(page)).audio.samplesPlaying).not.toContain('alarm');await page.screenshot({animations:'disabled',path:`${evidenceDir}/generator.png`});
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(62,107);g.setLook(Math.PI,-.37);});await expect(page.locator('#interaction')).toContainText('Rádio');await page.keyboard.press('e');await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().escapeClues.includes('frequency'));await page.screenshot({animations:'disabled',path:`${evidenceDir}/radio.png`});
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(1,7);g.setLook(0,0);g.setPhase('night');g.finishSpawning();for(let i=0;i<40;i++)g.spawn(-7+i%10*1.6,14+Math.floor(i/10)*1.6,['walker','walker','runner','spitter','tank','screamer'][i%6]);});await page.waitForTimeout(3000);const h=await state(page);rows.push({name:'night-horde',fps:h.fps,frameMs:1000/h.fps,calls:h.calls,triangles:h.triangles,entities:h.zombies.length,ai:h.zombies.length,audio:h.audio,render:h.render,director:h.director});expect(h.audio.peak).toBeLessThanOrEqual(16);await page.screenshot({animations:'disabled',path:`${evidenceDir}/night-horde.png`});expect(errors).toEqual([]);
 await writeFile(`${evidenceDir}/interiors-performance.json`,JSON.stringify({renderer:await page.evaluate(()=>{const gl=document.querySelector('canvas')!.getContext('webgl2')!;const e=gl.getExtension('WEBGL_debug_renderer_info');return e?gl.getParameter(e.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);}),quality:'low',rows,errors},null,2));
});
test('Phase 9 selected car impacts trigger one finite alarm without infinite reactivation',async({page})=>{
 test.setTimeout(90000);await start(page);
 const car=await page.evaluate(async()=>{const w=await import('/src/game/world.ts');return w.URBAN.vehicles.find((v:any)=>v.kind==='hatch'&&v.angle===0);});expect(car).toBeTruthy();
 await page.evaluate(car=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPlayer(car.x,car.z+car.d/2+4);g.setLook(Math.PI,-.1);g.setPhase('dusk');g.setHealth(1000);g.setBase(10000);},car);
 await page.waitForTimeout(500);await page.evaluate(()=>document.querySelector('canvas')!.dispatchEvent(new PointerEvent('pointerdown',{button:0,bubbles:true})));await page.waitForTimeout(350);await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointerup',{button:0,bubbles:true})));await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().audio.samplesPlaying.includes('alarm'));await page.screenshot({animations:'disabled',path:`${evidenceDir}/impact-alarm.png`});
 await page.waitForFunction(()=>!(window as any).__LAST_NIGHT__.state().audio.samplesPlaying.includes('alarm'),null,{timeout:40000});await page.evaluate(()=>document.querySelector('canvas')!.dispatchEvent(new PointerEvent('pointerdown',{button:0,bubbles:true})));await page.waitForTimeout(350);await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointerup',{button:0,bubbles:true})));expect((await state(page)).audio.samplesPlaying).not.toContain('alarm');
});
