import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
test('held Shift exhausts smoothly; pause, inventory, recovery and retry preserve control',async({page})=>{
 test.setTimeout(120000);await mkdir('docs/city',{recursive:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test');await page.locator('#start').click();await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.setPlayer(88,-30);g.clearWalkers();g.setPhase('dusk');});
 await page.keyboard.down('w');await page.keyboard.down('d');await page.keyboard.down('Shift');await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().player.exhausted,null,{timeout:40000});const zero=await page.evaluate(()=>(window as any).__LAST_NIGHT__.state());await page.waitForFunction(t=>(window as any).__LAST_NIGHT__.state().stats.seconds>t+.7,zero.stats.seconds);expect((await page.evaluate(()=>(window as any).__LAST_NIGHT__.state())).player.running).toBe(false);await page.keyboard.up('w');await page.keyboard.up('d');
 const exhausted=await page.evaluate(()=>(window as any).__LAST_NIGHT__.state().player);expect(exhausted.running).toBe(false);await page.keyboard.up('Shift');await page.keyboard.down('Shift');
 await page.keyboard.press('Escape');const frozen=await page.evaluate(()=>(window as any).__LAST_NIGHT__.state().player);await page.waitForTimeout(500);expect(await page.evaluate(()=>(window as any).__LAST_NIGHT__.state().player)).toEqual(frozen);await page.locator('#resume').click();
 await page.screenshot({path:'docs/city/exhaustion-after.png'});await page.keyboard.press('Tab');await expect(page.locator('#inventory-panel')).toBeVisible();await page.keyboard.press('Tab');
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;(window as any).__staminaAfter=[];const tick=()=>{const s=g.state();(window as any).__staminaAfter.push({...s.player,time:s.stats.seconds});if((window as any).__staminaAfter.length<100)requestAnimationFrame(tick);};requestAnimationFrame(tick);});
 await page.keyboard.down('s');await page.keyboard.down('a');await page.keyboard.down('Shift');await page.waitForFunction(()=>(window as any).__LAST_NIGHT__.state().player.running,null,{timeout:20000});await page.waitForFunction(p=>{const s=(window as any).__LAST_NIGHT__.state().player;return Math.hypot(s.x-p.x,s.z-p.z)>.7;},exhausted,{timeout:15000});await page.keyboard.up('s');await page.keyboard.up('a');await page.keyboard.up('Shift');const recovered=await page.evaluate(()=>(window as any).__LAST_NIGHT__.state().player);expect(recovered.exhausted).toBe(false);expect(recovered.stamina).toBeGreaterThan(10);expect(Math.hypot(recovered.x-exhausted.x,recovered.z-exhausted.z)).toBeGreaterThan(.5);
 await writeFile('docs/city/stamina-browser-after.json',JSON.stringify(await page.evaluate(()=>(window as any).__staminaAfter),null,2));
 await page.evaluate(()=>(window as any).__LAST_NIGHT__.setHealth(0));await expect(page.locator('#game-over')).toBeVisible();await expect(page.locator('#health')).toHaveText('0');await page.locator('#retry').click();const reset=await page.evaluate(()=>(window as any).__LAST_NIGHT__.state().player);expect(reset.stamina).toBe(100);expect(reset.exhausted).toBe(false);expect(errors).toEqual([]);
});
