import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const evidenceDir=process.env.UI_EVIDENCE_DIR??'docs/ui-theme';
const quality=process.env.UI_TEST_QUALITY??'low';
const rendering=(p:Page)=>p.evaluate(()=>{const gl=document.querySelector<HTMLCanvasElement>('#game')!.getContext('webgl2')!,info=gl.getExtension('WEBGL_debug_renderer_info');const settings=(window as any).__LAST_NIGHT__.state().settings;return {renderer:info?gl.getParameter(info.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),quality:settings.quality,shadows:settings.shadows};});
const read=(p:Page)=>p.evaluate(()=>(window as any).__LAST_NIGHT__.state());
// Chromium can require a fresh gesture after resizing or a recent Escape.
async function recapture(page:Page){await expect(async()=>{if(await page.locator('#capture-mouse').isVisible())await page.locator('#capture-mouse').click({timeout:1500});expect(await page.evaluate(()=>!!document.pointerLockElement)).toBe(true);}).toPass({timeout:8000});}
test('shared survival theme: original assets, menu, pause, inventory and responsive controls',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);await mkdir(evidenceDir,{recursive:true});await page.setViewportSize({width:1440,height:1080});await page.addInitScript(quality=>localStorage.setItem('last-night-settings',JSON.stringify({quality,shadows:quality!=='low',master:0})),quality);await page.goto('/?test',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!(window as any).__LAST_NIGHT__);
 await page.addStyleTag({content:'#debug-stats{display:none!important}'});await page.locator('#menu').screenshot({animations:'disabled',path:`${evidenceDir}/menu.png`});await page.locator('#menu-settings').click();await expect(page.locator('#settings-screen')).toBeVisible();await page.screenshot({animations:'disabled',path:`${evidenceDir}/settings.png`});await page.locator('#settings-close').click();await page.locator('#credits-open').click();await expect(page.locator('#credits-screen')).toBeVisible();await page.locator('#credits-close').click();await page.locator('#start').click();await page.waitForFunction(()=>!!document.pointerLockElement);
 await page.evaluate(()=>{const g=(window as any).__LAST_NIGHT__;g.clearWalkers();g.setPhase('dusk');g.setPlayer(88,-30);g.setLook(Math.PI,-.06);g.setInventory({ammo:79,med:1,wood:6,scrap:5});setInterval(()=>{g.clearWalkers();g.setPhase('dusk',0);},2000);});await page.keyboard.press('Tab');await expect(page.locator('#inventory-panel')).toBeVisible();await page.waitForFunction(()=>Array.from(document.querySelectorAll('.item-art')).every(i=>(i as HTMLImageElement).complete&&(i as HTMLImageElement).naturalWidth>0));await expect(page.locator('#item-ammo')).toHaveText('79');expect(await page.locator('.item-slot .item-art').count()).toBe(6);await page.screenshot({animations:'disabled',path:`${evidenceDir}/inventory-1440.png`});
 await page.locator('#select-med').click();await expect(page.locator('#detail-med')).toBeVisible();await page.locator('#equipment-tab').click();await expect(page.locator('#equipment-details')).toBeVisible();await page.screenshot({animations:'disabled',path:`${evidenceDir}/equipment.png`});await page.locator('#supplies-tab').click();await page.locator('#select-ammo').click();await page.locator('#discard-ammo').click();await expect(page.locator('#item-ammo')).toHaveText('67');await page.locator('#inventory-close').click();await page.waitForFunction(()=>!!document.pointerLockElement);await page.keyboard.press('Escape');await expect(page.locator('#pause-screen')).toBeVisible();await expect(page.locator('#inventory-panel')).toBeHidden();await page.screenshot({animations:'disabled',path:`${evidenceDir}/pause.png`});await page.locator('#pause-settings').click();await page.locator('#setting-uiScale').fill('1.2');await page.locator('#setting-uiScale').dispatchEvent('input');await page.locator('#settings-close').click();await page.locator('#resume').click();await page.waitForFunction(()=>!!document.pointerLockElement);
 const layouts=[];for(const [width,height] of [[1920,1080],[1366,768],[960,640],[640,640]]){await page.setViewportSize({width,height});await page.keyboard.press('Tab');await expect(page.locator('#inventory-close')).toBeInViewport();await page.locator('#select-scrap').click();await expect(page.locator('#detail-scrap')).toBeVisible();await page.locator('#inventory-panel footer').scrollIntoViewIfNeeded();await expect(page.locator('#inventory-panel footer')).toBeInViewport();layouts.push({width,height,box:await page.locator('#inventory-panel').boundingBox()});await page.locator('#inventory-panel').evaluate(el=>el.scrollTop=0);await page.screenshot({animations:'disabled',path:`${evidenceDir}/inventory-${width}.png`});await page.locator('#inventory-close').click();await recapture(page);}
 expect(errors).toEqual([]);await writeFile(`${evidenceDir}/validation.json`,JSON.stringify({...await rendering(page),requestedQuality:quality,errors,layouts,checks:['menu','settings','credits','pause','six provided item images loaded','selection','tabs','discard updates inventory','close and pointer lock','scrollable inventory at 1.2 UI scale']},null,2));
});

test('two real Photon clients share the inventory, pause and lobby theme',async({browser})=>{
 const pages:Page[]=[],errors:string[]=[];await mkdir(evidenceDir,{recursive:true});
 try{
  for(const name of ['Bann','Companheiro']){
   const context=await browser.newContext({viewport:{width:1440,height:1080}}),p=await context.newPage();pages.push(p);p.setDefaultTimeout(30000);p.on('pageerror',e=>errors.push(e.message));
   await p.addInitScript(({name,quality})=>{localStorage.setItem('last-night-settings',JSON.stringify({quality,shadows:quality!=='low',master:0}));localStorage.setItem('last-night-player-name',name);},{name,quality});
   await p.goto('/?test',{waitUntil:'domcontentloaded'});await p.addStyleTag({content:'#debug-stats{display:none!important}'});await p.locator('#coop-online').click();await expect(p.locator('#coop-create')).toBeEnabled({timeout:60000});
  }
  const [a,b]=pages;await a.locator('#coop-create').click();await expect(a.locator('#coop-lobby')).toBeVisible();const code=await a.locator('#coop-room-code').innerText();await b.locator('#coop-code-input').fill(code);await b.locator('#coop-join').click();await expect(b.locator('#coop-lobby')).toBeVisible();await b.locator('#coop-ready').click();await expect(a.locator('#coop-start')).toBeEnabled();await a.screenshot({animations:'disabled',path:`${evidenceDir}/coop-lobby.png`});await a.locator('#coop-start').click();
  for(const p of pages){await expect.poll(async()=>(await read(p)).network.state,{timeout:60000}).toBe('playing');await expect.poll(async()=>(await read(p)).coop?.revision??0).toBeGreaterThan(0);}
  await a.evaluate(async()=>{const w=(window as any).__LAST_NIGHT__.coopFixture();const {CITY_SITES}=await import('/src/game/city.ts');w.sim.zombies=[];w.sim.activatedSites=new Set(CITY_SITES.map(s=>s.id));});
  for(const [i,p] of pages.entries()){
   await p.bringToFront();if((await read(p)).paused)await p.locator('#resume').click();else if(!(await read(p)).camera.pointerLocked)await p.locator('#capture-mouse').click();await p.waitForFunction(()=>!!document.pointerLockElement);await p.keyboard.press('Tab');await expect(p.locator('#inventory-panel')).toBeVisible();await expect(p.locator('#app')).toHaveClass(/coop-playing/);expect(await p.locator('#inventory-panel').evaluate(el=>getComputedStyle(el).backgroundImage)).toContain('distressed-panel.png');expect(await p.locator('.item-slot .item-art').count()).toBe(6);await p.waitForFunction(()=>Array.from(document.querySelectorAll('.item-art')).every(i=>(i as HTMLImageElement).complete&&(i as HTMLImageElement).naturalWidth>0));await p.locator('#select-med').click();await expect(p.locator('#detail-med')).toBeVisible();await p.locator('#equipment-tab').click();await expect(p.locator('#equipment-details')).toBeVisible();await p.locator('#supplies-tab').click();await p.locator('#select-ammo').click();await p.screenshot({animations:'disabled',path:`${evidenceDir}/coop-inventory-${i+1}.png`});await p.locator('#inventory-close').click();await p.waitForFunction(()=>!!document.pointerLockElement);await p.keyboard.press('Escape');await expect(p.locator('#pause-description')).toContainText('companheiros continuam');await expect(p.locator('#inventory-panel')).toBeHidden();await p.screenshot({animations:'disabled',path:`${evidenceDir}/coop-pause-${i+1}.png`});await p.locator('#pause-settings').click();await expect(p.locator('#settings-screen')).toBeVisible();await p.locator('#settings-close').click();await p.locator('#resume').click();await p.waitForFunction(()=>!!document.pointerLockElement);
  }
  expect(errors).toEqual([]);const clients=await Promise.all(pages.map(rendering));await writeFile(`${evidenceDir}/coop-validation.json`,JSON.stringify({...clients[0],requestedQuality:quality,clients,players:2,transport:'Photon Realtime',checks:['private lobby and ready controls','shared panel texture on both clients','six item images loaded on both clients','selection and equipment tabs','pause messaging and settings','resume pointer lock'],errors},null,2));
 }finally{for(const p of pages)await p.context().close();}
});
