import { icon, emblem } from './icons';
import { ITEMS, itemKeys } from '../game/inventory';
const button=(id:string,label:string,kind='menu-link')=>`<button id="${id}" class="${kind}">${label}${icon('arrow')}</button>`;
const controls=[['WASD','Mover'],['Shift','Correr'],['Mouse','Mirar'],['Clique','Disparar'],['R','Recarregar'],['1 / 2','Arma longa / curta'],['E','Interagir / reparar'],['H','Usar bandagem'],['Tab','Mochila'],['M','Mapa'],['F','Lanterna'],['X','Desmontar defesa'],['Esc','Pausar']];
export const layout=():string=>`
<canvas id="game" tabindex="-1" aria-label="LAST NIGHT — cenário 3D do jogo"></canvas>
<div class="vignette"></div><div id="damage-vignette"></div><div id="low-health-edge"></div>
<div class="game-ui in-game">
  <header class="topbar"><div class="brand">${emblem}<span>LAST NIGHT</span></div><div class="top-actions"><button id="sound" class="icon-button" aria-label="Desativar som" title="Som">${icon('sound')}</button><button id="pause" class="icon-button" aria-label="Pausar jogo" title="Pausar · Esc">${icon('pause')}</button></div></header>
  <section id="cycle" class="cycle" aria-label="Ciclo do dia"><svg class="cycle-dial" viewBox="0 0 96 64"><path class="dial-track" d="M8 48a40 40 0 0 1 80 0"/><path id="cycle-line" d="M8 48a40 40 0 0 1 80 0" pathLength="100"/><path class="dial-ticks" d="M8 48h6m68 0h6M19 20l4 4M48 8v6m29 6-4 4"/></svg><span id="phase-icon">${icon('sun')}</span><span id="day">Dia 01</span><strong id="phase">Luz do dia</strong><div class="clock-readout"><span id="timer-label">Anoitecer em</span><strong id="timer">04:00</strong></div></section>
  <section id="objective" class="objective"><i></i><div><h2 id="objective-title">Antes que escureça</h2><p id="objective-sub">Encontre suprimentos e volte ao abrigo.</p></div></section>
  <section class="base-status">${icon('shelter')}<div><span>Abrigo</span><div class="base-track"><i id="base-bar"></i></div></div><b id="base-hp">1000</b></section>
  <div id="threat" class="threat" hidden><span id="threat-label">Defenda o abrigo</span><div class="horde-track"><i id="horde-bar"></i></div></div>
  <footer class="bottom-hud"><section class="survivor-panel"><div class="survivor-stamp">${emblem}<small>VIVO</small></div><div class="vitals"><div class="vital-title"><span id="health-state">Sem ferimentos</span><strong id="health">100</strong>${icon('health')}</div><div class="health-track"><i id="health-bar"></i></div><div id="stamina" class="stamina-row">${icon('stamina')}<div class="stamina-track"><i id="stamina-bar"></i></div><span id="stamina-label">Fôlego</span></div></div></section>
  <button id="bag-toggle" class="resource-strip" aria-label="Abrir mochila"><span class="bag-key">${icon('bag')}<kbd>Tab</kbd></span>${(['wood','scrap','med'] as const).map(k=>`<span title="${ITEMS[k].label}">${icon(k)}<b id="resource-${k}">0</b></span>`).join('')}</button></footer>
  <section class="weapon-panel"><div class="weapon-top"><span class="weapon-icon">${icon('gun')}</span><div><span class="weapon-name">Pistola</span><small>9 mm · semiautomática</small></div><div class="weapon-slots" aria-label="Equipamento"><button id="slot-1" class="selected" aria-label="Pistola equipada">1</button><button id="slot-2" aria-label="Arma secundária indisponível" disabled>2</button><button id="slot-3" aria-label="Utilidade indisponível" disabled>3</button></div></div><div class="ammo"><strong id="ammo">12</strong><div class="ammo-reserve"><b id="reserve">60</b><small>reserva</small></div><span id="reload-label"><kbd>R</kbd> Recarregar</span></div><div id="cartridges" class="cartridges">${Array.from({length:12},()=>'<i></i>').join('')}</div><div class="reload-track"><i id="reload-bar"></i></div></section>
  <button id="map-toggle" class="minimap-panel" aria-label="Abrir mapa de Santa Luz"><span class="map-title"><b>Santa Luz</b><span>N ↑</span></span><canvas id="minimap" width="360" height="300" aria-label="Mapa: ruas, locais conhecidos, abrigo e sua posição"></canvas><span class="map-footer"><span id="region-name">Abrigo</span><kbd>M</kbd></span></button>
  <div id="tutorial" class="tutorial"></div><div id="loot-feed" class="loot-feed" role="status" aria-live="polite"></div><div id="danger-edge" class="danger-edge" hidden>${icon('danger')}<span>Passos próximos</span></div>
</div>
<div id="notice" class="notice" role="status"><span class="notice-dash"></span><h2 id="notice-title"></h2><p id="notice-sub"></p></div>
<div id="interaction" class="interaction" role="status"></div><div id="crosshair" aria-hidden="true"><i></i><i></i><i></i><i></i><b></b></div>
<section id="menu" class="menu"><div class="menu-shade"></div><div class="menu-content"><div class="menu-emblem">${emblem}<span>Santa Luz<br><small>Depois da evacuação</small></span></div><h1>LAST<br><span>NIGHT</span></h1><p class="tagline">Só mais uma noite.</p><nav>${button('start','Jogar','primary')}${button('menu-settings','Configurações')}${button('credits-open','Créditos')}</nav><p class="menu-note">Encontre o que resta.<br>Proteja seu lugar no mundo.</p></div><div class="menu-bottom"><span>Sobrevivência em Santa Luz</span><span>Uma expedição de cada vez.</span></div></section>
<section id="pause-screen" class="modal" hidden aria-label="Jogo pausado"><div class="pause-card"><span class="eyebrow">LAST NIGHT / pausa</span><h2>Respire.</h2><p>A cidade pode esperar.</p><nav>${button('resume','Continuar','primary')}${button('pause-settings','Configurações')}${button('restart','Reiniciar expedição')}${button('pause-menu','Sair para o menu')}</nav><div class="quick-quality"><span>Qualidade visual</span><button id="quality" class="text-button">Alta</button></div><small><kbd>Esc</kbd> Continuar</small></div></section>
<section id="settings-screen" class="modal" hidden aria-label="Configurações"><div class="settings-card"><header><div><span class="eyebrow">Ajuste seu equipamento</span><h2>Configurações</h2></div><button id="settings-close" class="icon-button" aria-label="Fechar configurações">${icon('close')}</button></header><div class="settings-columns"><section><h3>${icon('sound')} Áudio</h3>${[['master','Volume geral'],['music','Música'],['effects','Efeitos']].map(([id,label])=>`<label class="setting-range">${label}<output id="value-${id}"></output><input id="setting-${id}" aria-label="${label}" type="range" min="0" max="100" step="5"></label>`).join('')}<label class="setting-toggle"><input type="checkbox" id="setting-captions">Legendas de eventos</label><h3>${icon('map')} Controles</h3><label class="setting-range">Resposta da mira<output id="value-sensitivity"></output><input id="setting-sensitivity" aria-label="Resposta da mira" type="range" min="0.5" max="1.5" step="0.1"></label><p class="setting-help">Velocidade do acompanhamento visual. O cursor mantém a posição exata.</p></section><section><h3>${icon('settings')} Imagem</h3><label class="setting-select">Qualidade<select id="setting-quality"><option value="high">Alta</option><option value="low">Leve</option></select></label><label class="setting-toggle"><input type="checkbox" id="setting-shadows">Sombras</label><label class="setting-toggle"><input type="checkbox" id="setting-shake">Movimento de câmera nos impactos</label><label class="setting-range">Tamanho da interface<output id="value-uiScale"></output><input id="setting-uiScale" aria-label="Tamanho da interface" type="range" min="0.85" max="1.2" step="0.05"></label><button id="fullscreen" class="text-button">Tela cheia</button><p id="fullscreen-status" role="status"></p></section></div><details class="controls-help"><summary>Teclas e ações</summary><div>${controls.map(([key,label])=>`<span><kbd>${key}</kbd>${label}</span>`).join('')}</div></details><p class="settings-saved">Ajustes salvos neste navegador.</p></div></section>
<section id="credits-screen" class="modal" hidden><div class="pause-card">${emblem}<h2>LAST NIGHT</h2><p>Uma cidade que ficou para trás.<br>Um abrigo que ainda resiste.</p><p>Modelos voxel, ícones e áudio procedural criados para este projeto.</p><p>Construído com Three.js.<br>Tipografia Noto Sans · SIL Open Font License.</p>${button('credits-close','Voltar','primary')}</div></section>
<section id="game-over" class="modal end-screen" hidden><div class="end-card"><span class="eyebrow">Último registro</span><h2 id="end-title">Você não sobreviveu à noite.</h2><p id="end-reason"></p><div class="end-stats"><span>Dia alcançado<strong id="end-days">01</strong></span><span>Eliminações<strong id="end-kills">00</strong></span><span>Tempo vivo<strong id="end-time">00:00</strong></span></div><div id="end-details"></div><nav>${button('retry','Tentar novamente','primary')}${button('end-menu','Menu')}</nav></div></section>
<section id="inventory-panel" class="inventory-panel" hidden aria-label="Inventário"><header class="inventory-heading"><div class="inventory-title">${icon('bag')}<div><span class="eyebrow">Equipamento de campo</span><h2>Mochila</h2></div></div><button id="inventory-close" class="icon-button" aria-label="Fechar inventário">${icon('close')}</button></header><div class="capacity"><span>Espaço disponível</span><strong id="capacity-label"></strong><i><b id="capacity-bar"></b></i></div><div class="inventory-items" role="group" aria-label="Recursos">${itemKeys.map((k,i)=>`<button id="select-${k}" class="item-slot ${i===0?'selected':''}" aria-pressed="${i===0}" data-item="${k}">${icon(k)}<strong id="item-${k}">0</strong><span>${ITEMS[k].label}</span></button>`).join('')}<div class="empty-slot">${icon('bag')}<span>Viaje leve.</span></div></div><div id="item-details">${itemKeys.map((k,i)=>`<article id="detail-${k}" ${i?'hidden':''}><header>${icon(k)}<h3>${ITEMS[k].label}</h3><span>${ITEMS[k].weight.toLocaleString('pt-BR')} kg</span></header><p>${ITEMS[k].hint}</p><div class="item-actions"><button id="deposit-${k}" class="storage-action">${icon('deposit')} Guardar</button><button id="withdraw-${k}" class="storage-action">${icon('withdraw')} Retirar ${ITEMS[k].step}</button><button id="discard-${k}" title="Descartar ${ITEMS[k].step}">${icon('discard')} Largar ${ITEMS[k].step}</button></div><span class="storage-action stored-count" id="stored-${k}"></span></article>`).join('')}</div><div class="inventory-use"><button id="use-med">${icon('med')} Usar bandagem <kbd>H</kbd></button><button id="use-rare">${icon('shelter')} Reforçar abrigo</button></div><footer><p id="inventory-context"></p><span class="live-indicator"></span> O mundo continua lá fora.</footer></section>
<section id="map-screen" class="map-screen" hidden aria-label="Mapa de Santa Luz"><div class="map-sheet"><header><div><span class="eyebrow">Guia de campo / região urbana</span><h2>Santa Luz</h2></div><button id="map-close" class="icon-button" aria-label="Fechar mapa">${icon('close')}</button></header><div class="map-body"><canvas id="full-map" width="900" height="900" aria-label="Mapa completo de Santa Luz"></canvas><aside><span class="eyebrow">Locais de referência</span><div id="map-legend"></div><p>O traço claro marca os lugares por onde você passou.</p><p class="map-live">O mapa não pausa a expedição.</p></aside></div><footer><span>${icon('shelter')} Abrigo &nbsp; · &nbsp; △ Você</span><span><kbd>M</kbd> Guardar mapa</span></footer></div></section>
<div id="load-error" class="modal" hidden><div class="pause-card"><h2>Não foi possível iniciar.</h2><p id="error-detail"></p>${button('reload-page','Tentar novamente','primary')}</div></div>`;
