/** Typed subset verified against Photon JS 4.4 and the official LoadBalancing reference. */
declare module 'photon-realtime' {
 export interface Actor {actorNr:number;name:string;isLocal:boolean;getCustomProperty(key:string):unknown;setName(name:string):void;setCustomProperties(data:Record<string,unknown>):void;setCustomProperty(key:string,value:unknown):void}
 export interface Room {name:string;masterClientId:number;isOpen:boolean;maxPlayers:number;getCustomProperty(key:string):unknown;setCustomProperties(data:Record<string,unknown>,webForward?:boolean,expected?:Record<string,unknown>):void;setCustomProperty(key:string,value:unknown):void;setIsOpen(value:boolean):void}
 export interface Peer {setLogLevel(level:number):void;addPeerStatusListener(code:string,callback:()=>void):void;connect(appId?:string):void;disconnect():void;Destroy():void;ping():void;getRtt():number}
 export interface Client {onStateChange:(state:number)=>void;onError:(code:number,message:string)=>void;onOperationResponse:(error:number,message:string,operation:number,content:unknown)=>void;onEvent:(code:number,data:unknown,actor:number)=>void;onJoinRoom:(created:boolean)=>void;onActorJoin:(actor:Actor)=>void;onActorLeave:(actor:Actor,cleanup:boolean)=>void;onActorPropertiesChange:(actor:Actor)=>void;onMyRoomPropertiesChange:()=>void;onGetRegionsResult:(error:number,message:string,regions:Record<string,string>)=>void;setUserId(id:string):void;getUserId():string;setLogLevel(level:number):void;connectToNameServer():boolean;connectToRegionMaster(region:string):boolean;getRegions():void;disconnect():void;state():number;myActor():Actor;myRoom():Room;myRoomMasterActorNr():number;updateRtt():void;myRoomActors():Record<number,Actor>;isJoinedToRoom():boolean;createRoom(name:string,options:Record<string,unknown>):boolean;joinRoom(name:string,options?:Record<string,unknown>):boolean;raiseEvent(code:number,data:unknown,options?:Record<string,unknown>):void;getRtt():number}
 const Photon:{ConnectionProtocol:{Wss:number};PhotonPeer:{new(protocol:number,address:string,subprotocol?:string,debugName?:string):Peer;setWebSocketImpl(impl:typeof WebSocket):void;StatusCodes:Record<string,string>};LoadBalancing:{LoadBalancingClient:{new(protocol:number,appId:string,version:string):Client;State:Record<string,number>;StateToName(state:number):string};Constants:{ReceiverGroup:{Others:number;All:number}}}};
 export default Photon;
}
